### ISSUE TITLE
raml-to-jaxrs generator doesn't resolve nested relative JSON schemas.

### ISSUE THREAD

**Issue by vanDonselaar** [mulesoft-labs/raml-for-jax-rs#125]
Have a look at this minimal example:
https://github.com/zivver/raml-for-jax-rs-maven-plugin-bug
I don't think this behavior is desired. What would be the best way to solve this problem?

**Comment by jpbelang** [comment]
This should work in 2.0

**Comment by zeljkot** [comment]
This happens again with 3.0.5.
