### ISSUE TITLE
make use existsing java classes in RAML

### ISSUE THREAD

**Issue by cforce** [mulesoft-labs/raml-for-jax-rs#126]
We use a Java Class MyJavaType  that can has fromString() and toString() method, so i can be used in Jax-RS anotation as PathParam of type String. The auto boxing of String on the wire to MyJavaType is done by CXF.
How can we define or just use MyJavaType (which already exists as type in Java sourcde as PathParam/QueryParam?

**Comment by jpbelang** [comment]
This is could be done through plugins (if still relevant). 2.2 will have better plugins.
