### ISSUE TITLE
No value has been specified for property 'jsonMapperConfiguration'.

### ISSUE THREAD

**Issue by KIC** [mulesoft-labs/raml-for-jax-rs#147]
Since I was not able to get this plugin from maven repos I have built it from source (1.3.4-SNAPSHOT). Forthe follwoing configuration I will get a gradle exception "No value has been specified for property 'jsonMapperConfiguration'."

raml {
    basePackageName = 'some.package'
    jaxrsVersion = '2.0'
    jsonMapper = 'JACKSON2'
    outputDirectory = new File('src/main/gen-src')
    sourceDirectory = new File('src/main/resources/raml')
    sourcePaths = null // The set of source .raml and .yaml files in addition to those found in the source directory
    //jsonMapperConfiguration = null
    useJsr303Annotations = false
    asyncResourceTrait = false
}

What do I need to fill into the jsonMapperConfiguration property?

**Comment by matt1as** [comment]
For what it's worth I added 
  jsonMapperConfiguration= ["useLongIntegers" : true]
 and it seems to work

From this link https://github.com/mulesoft/raml-for-jax-rs/issues/92
