### ISSUE TITLE
Add support for `@MatrixParam`s

### ISSUE THREAD

**Issue by t1** [mulesoft-labs/raml-for-jax-rs#149]
I guess this requires support by the spec. See [issue-187](https://github.com/raml-org/raml-spec/issues/187).

**Comment by t1** [comment]
I'm not allowed to label this issue as [Cookie&Matrix params](https://github.com/mulesoft/raml-for-jax-rs/labels/Cookie%26Matrix%20params), so it would be found when following the [link from the README](https://github.com/mulesoft/raml-for-jax-rs#jax-rs-annotations)... (and that link should be updated from `...&state=closed` to `...&state=open`).

**Comment by jpbelang** [comment]
Does the spec support these explicitely ?
