### ISSUE TITLE
the generated Response Wrapper is for JAX-RS 1.1 while I set <JAX-RSVersion>2.0</JAX-RSVersion>

### ISSUE THREAD

**Issue by wenlonglwl** [mulesoft-labs/raml-for-jax-rs#153]
rt

**Comment by jgoyer3304** [comment]
I have also run into this issue with using RAML maven plugin 1.3.4.  Is this a question of the generators for 2.0 not being written yet?  My understanding that javax.ws.rs-api is 2.0 compliance and jsr311-api is 
1.1.  I see this project uses JSR-311.  Has the work been done to move it to 2.0?

**Comment by marcinwaldowski** [comment]
For version `1.3.4` of `raml-jaxrs-maven-plugin` use `<jaxrsVersion>2.0</jaxrsVersion>` instead of `<JAX-RSVersion>2.0</JAX-RSVersion>`.

**Comment by cbchhaya** [comment]
Tried that, still get the error.

raml-jaxrs-maven-plugin depends on raml-jaxrs-codegen-core of the same version. raml-jaxrs-codegen-core v1.3.4 has a dependency on jsr311:
http://search.maven.org/#artifactdetails%7Corg.raml%7Craml-jaxrs-codegen-core%7C1.3.4%7Cjar

Adding an explicit exclusion for jsr311, and adding a dependency on javax.ws.rs-api 2.0 seems to do the trick.

Also I think the inclusion of jsr311 in the [pom.xml](https://github.com/mulesoft/raml-for-jax-rs/blob/master/raml-to-jaxrs/examples/raml-maven-plugin-example/pom.xml) for the maven example is perhaps confusing:

**Comment by jpbelang** [comment]
2.0 is 2.0.
