### ISSUE TITLE
Empty class is generated when i use oneOf,anyOf or allOf in the json schema

### ISSUE THREAD

**Issue by nlkvarma** [mulesoft-labs/raml-for-jax-rs#185]
I am trying to generate java classes form the raml file which has included json schema files. when i  use oneOf,anyOf or allOf in the json schema file, corresponding empty java class is generated without any fields.

**Comment by vanDonselaar** [comment]
`raml-for-jax-rs` uses `jsonschema2pojo` internally for POJO generation. There is no support yet for oneOf, anyOf and allOf as far as I know. See their wiki page for a proposal: https://github.com/joelittlejohn/jsonschema2pojo/wiki/Proposal-for-allOf,-anyOf-and-oneOf
