### ISSUE TITLE
1.3.5-SNAPSHOT Deleted from Maven

### ISSUE THREAD

**Issue by th3morg** [mulesoft-labs/raml-for-jax-rs#187]
It appears someone has deleted the 1.3.5-SNAPSHOT version from maven. 1.3.3 and 1.3.4 don't work because of the error from issue https://github.com/mulesoft/raml-for-jax-rs/issues/84

Can 1.3.5 please be release or can the snapshot please be published?

Thank you.

**Comment by petrochenko-pavel-a** [comment]
Hi, @th3morg looking in this right now.

will republish it asap.

Regards,
Pavel

**Comment by petrochenko-pavel-a** [comment]
published 1.3.5-SNAPSHOT.

**Comment by Blackbilbao** [comment]
It's still not available 
neither via Maven nor via your own Repository (via snapshots or realeses)

Pls Fix

**Comment by zerok** [comment]
Sadly still not available :(
