### ISSUE TITLE
Schema $ref should be able to reference files local to the schema

### ISSUE THREAD

**Issue by benlei-neustar** [mulesoft-labs/raml-for-jax-rs#189]
It looks likes one schema cannot reference another local schema:

```
{
    "$ref": "file:someSchema.schema"
}
```

And the reason this seems to fail is because the files are copied to a different directory with an obfuscated name.

**Comment by vanDonselaar** [comment]
Hi @benlei-neustar, I've had a similar problem, I think it's the same: https://github.com/mulesoft/raml-for-jax-rs/issues/125

I've created a minimum working example here: https://github.com/zivver/raml-for-jax-rs-maven-plugin-bug Have a look at the workaround there.

**Comment by jstoiko** [comment]
FTR, this works as expected using version 2. JSON schemas are processed by jsonschema2pojo so the $ref has to follow what's described [here](https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference#ref).
