### ISSUE TITLE
Maven : Cannot compile on Mac

### ISSUE THREAD

**Issue by Lucky-Jim** [mulesoft-labs/raml-for-jax-rs#195]
When compiling for a mac using maven - I continuously get the following:

_[ERROR] Failed to execute goal org.raml.plugins:raml-jaxrs-maven-plugin:1.3.4:generate (default) on project ShippedService: Error generating Java classes from: /Users/tburnley/git/client_reference/api_definition/workspace/raml/api.raml: Unrecognised URI, can't resolve this: file:/var/folders/0v/93409b0155b95lcxw8jmjnd40000gn/T/1469456379621-0/booking.schema: /var/folders/0v/93409b0155b95lcxw8jmjnd40000gn/T/1469456379621-0/**booking.schema** (No such file or directory) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.raml.plugins:raml-jaxrs-maven-plugin:1.3.4:generate (default) on project ShippedService: Error generating Java classes from: /Users/tburnley/git/client_reference/api_definition/workspace/raml/api.raml_

I presume that parser is not finding the highlighted booking schema file in the temporary directory that the maven plugin seems to create. The maven plugin definitely sees booking.schema earlier in the process : 

_[DEBUG] Looking for resource: /Users/tburnley/git/client_reference/api_definition/workspace/raml/schemas/booking.schema on directory: /Users/tburnley/git/client_reference/api_definition/workspace/raml...
[DEBUG] Looking for resource: /Users/tburnley/git/client_reference/api_definition/workspace/raml/schemas/booking.schema on directory: /Users/tburnley/git/client_reference/api_definition/workspace/raml...
[DEBUG] Looking for resource: /Users/tburnley/git/client_reference/api_definition/workspace/raml/schemas/booking.schema on directory: ...
[DEBUG] No encoding detected, using default: UTF-8_

Its almost as if it is not accessible in the temp directory - could this be something to do with the mac implementation uses temp directories?

**Comment by brs-mule** [comment]
Hello Lucky-Jim!

Thank you for submitting this issue. I am looking at the problem, but cannot reproduce it with my own sample RAML files. Could you possibly let us have your example project so that we can reproduce the issue?
