### ISSUE TITLE
generated path when @path is a concatenation of constants doesn't seem to work

### ISSUE THREAD

**Issue by ujjwal-gupta** [mulesoft-labs/raml-for-jax-rs#198]
path is generated perfectly when it is a string constant but when its a concatenation of two constant's it generates the following:
for:
@path(ConstantsClass.CONST_1 + ConstantsClass.CONST_2)

path in RAML file:
"/(package.ConstantsClass.CONST_1) + (package.ConstantsClass.CONST_2)"

**Comment by BluetriX** [comment]
Same here! Constants are not Resolved in the Path-Annotation:
@Path(UserBeanKey.USER_KEY + "/" + UserBean.REL_COMPANY)

results:
'/v{version}/users/(((com.example.user.UserBeanKey.USER_KEY) + "/") + (com.example.user.UserBean.REL_MAIN_ACCOUNT_MANAGER)) + "/{advisorUserNr}"':

**Comment by jstoiko** [comment]
@ujjwal-gupta @BluetriX have you tried this the new [2.0.0 version in the works](https://github.com/mulesoft-labs/raml-for-jax-rs/tree/release/2.0.0)? Feel free to give it a try and update this issue. It should work as expected now. If not, we'll address it before the GA release.
