### ISSUE TITLE
Enum generation is not Consistent

### ISSUE THREAD

**Issue by idefixcert** [mulesoft-labs/raml-for-jax-rs#205]
If we generate an Enum for a resource:
`enum: ["kurz","hilfe","lang","key"]`
we get

```
public enum Style {

        kurz,
        hilfe,
        lang,
        key;

    }
```

And thats really good, because the jackson parsen can handle this.

But if we have an enum in an schema file
`"style":  { "enum": ["kurz","hilfe","lang","key"] },`

we get:

```
public static enum Style {

        KURZ("kurz"),
        HILFE("hilfe"),
        LANG("lang"),
        KEY("key");
        private final String value;
        private final static Map<String, Enum.Style> CONSTANTS = new HashMap<String, Enum.Style>();

        static {
            for (Enum.Style c: values()) {
                CONSTANTS.put(c.value, c);
            }
        }

        private Style(String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return this.value;
        }

        public static Enum.Style fromValue(String value) {
            Enum.Style constant = CONSTANTS.get(value);
            if (constant == null) {
                throw new IllegalArgumentException(value);
            } else {
                return constant;
            }
        }

    }

```

And thats a problem for the jackson pasrser:
`Enum$Style from String value 'lang': value not one of declared Enum instance names: [kurz, hilfe, lang, key]`
Because in that case you have to set the name to "LANG"

**Comment by jstoiko** [comment]
Sorry for making you wait so long to get an answer but we've been working on a new version of `raml-for-jax-rs` with RAML 1.0 support.

If it's not too late, you can check this [example](https://github.com/mulesoft-labs/raml-for-jax-rs/tree/release/2.0.0/raml-to-jaxrs/examples/maven-examples/raml-defined-example) to get you started. Then you can try adding a JSON schema with an `enum` to see what it generates. Feel free to update this issue.
