### ISSUE TITLE
Support more of jsonschema2pojo's configuration parameters

### ISSUE THREAD

**Issue by KaiSchwier** [mulesoft-labs/raml-for-jax-rs#210]
Hi,

would it be possible to support more of jsonschema2pojos configuration options, like classNamePrefix, classNameSuffix (I know you can work around this with "javaType", but it is not that clean), maybe also customRuleFactory to allow full customization, or some of the others which are also available.
See https://joelittlejohn.github.io/jsonschema2pojo/site/0.4.27/generate-mojo.html

With bests
Kai

**Comment by jstoiko** [comment]
The new (upcoming) version has more, [here's the list](https://github.com/mulesoft/raml-for-jax-rs/blob/release/2.0.0/raml-to-jaxrs/examples/maven-examples/simple-json-example/README.md). Feel free to try it and tell us if you're missing anything.
