### ISSUE TITLE
Add RAML 1.0 support to jaxrs-to-raml

### ISSUE THREAD

**Issue by jstoiko** [mulesoft-labs/raml-for-jax-rs#212]
Work-in-progress: https://github.com/mulesoft/raml-for-jax-rs/tree/release/2.0.0

- [x] Extract relevant information from classes/code
- [x] Generate a `__raml__` interface for each JAX-RS defined types
- [x] Generate RAML 1.0 from JAX-RS code (CLI)
- [x] Extracting JaxRs resources from a set of compiled classes
- [x] Support for @Path classes and methods
- [x] Support for most HTTP verbs (HEAD, POST, GET, DELETE, PUT, OPTIONS)
- [x] Support for media types @Consumes and @Produces. The default media type is that of JaxRs and is listed as such in the RAML generated. Any method that has a different media type is explicitly declared as such and it is properly generated in the RAML.
- [x] Support for @QueryParam
- [x] Support for @PathParam
- [x] Support for @HeaderParam
- [x] Default values
- [x] Maven plugin that allows to parse compiled classes into RAML
- [x] CLI with same functionalities as the maven plugin
- [x] Support more than primitive types (complex objects) in return values
- [x] Support for @FormParam
- [x] Validations
- [x] Javadoc for descriptions
- [x] XML and Json stub generations -> Examples are generated as RAML data types

**Comment by PhilLavoie** [comment]
Hi, I can't edit the above list so I'll just insert my own here :):

- [x] Extracting JaxRs resources from a set of compiled classes
- [x] Support for @Path classes and methods
- [x] Support for most HTTP verbs (HEAD, POST, GET, DELETE, PUT, OPTIONS)
- [x] Support for media types @Consumes and @Produces. The default media type is that of JaxRs and is listed as such in the RAML generated. Any method who has a different media type is explicitly declared as such and it is properly generated in the RAML.
- [x] Support for @QueryParam
- [ ] Support for @FormParam. Seems like it doesn't translate to RAML 1.0? Need to figure out what is the mapping.
- [ ] Javadoc for descriptions
- [x] Default values
- [ ] Validations
- [ ] XML and Json stub generations
- [x] Maven plugin that allows to parse compiled classes into RAML
- [x] CLI with same functionalities as the maven plugin

Nothing Swagger related is supported as of yet.

**Comment by jstoiko** [comment]
thanks @PhilLavoie!

**Comment by sichvoge** [comment]
@jstoiko the mapping for form parameters usually is a simple `object` type with `properties`.

**Comment by ujjwal-gupta** [comment]
What about support for Annotation types as per [RAML Issue 174](https://github.com/raml-org/raml-spec/issues/174). Being able to mark an endpoint as deprecated is particularly useful.
