### ISSUE TITLE
Other RAML 1.0 concerns

### ISSUE THREAD

**Issue by jstoiko** [mulesoft-labs/raml-for-jax-rs#213]
Work-in-progress: https://github.com/mulesoft/raml-for-jax-rs/tree/release/2.0.0

- [x] Maven plugin, more examples
- [x] Address potential corner cases specific to RAML 1.0
- [x] Maven plugins
- [x] plugins to extend code generation (`GeneratorExtension`)
- [x] More testing/polishing
- [x] Add more examples
- [x] Update docs

**Comment by mplanchant** [comment]
Dare I ask when 2.0.0 is likely to be released?

**Comment by jstoiko** [comment]
End-of-the-month (of March) is the goal for GA. 

Are there any features - listed or not listed in [1 of these 3 issues](https://github.com/mulesoft-labs/raml-for-jax-rs/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0.0) - that you'd say is top-priority for you?

**Comment by mplanchant** [comment]
I'm interested in raml-to-jaxrs which looks as though it is mostly complete. It would be nice if the POJOs generated from RAML Data Types had builders, hashCode, equals, toString etc.
