### ISSUE TITLE
raml-jaxrs-maven-plugin: RAML queryParameters: Option missing for Long instead of integer

### ISSUE THREAD

**Issue by Sevyls** [mulesoft-labs/raml-for-jax-rs#214]
Refering to #133 

```
get:
    queryParameters:
      id:
        type: integer
```

RAML specifies only integer as a value type - not its limitations i.e. in Java.

The raml-jaxrs-maven-plugin generates attributes with Type Integer:

```
class Resource {
Resource.Response getResource(@QueryParam("id") Integer id) throws Exception ... 
```

There is currently no option to provide an override in queryParameters to generate Long instead of Integer parameters. In JSON Mapper it is already existing.

A feature to configure the maven plugin to generate Long values instead of Integers should be provided.

**Comment by jstoiko** [comment]
@Sevyls: there is a new version [in the works](https://github.com/mulesoft/raml-for-jax-rs/milestone/1). The goal is to add support for RAML 1.0 while being backward compatible with RAML 0.8. The plan is to address the specific issue you described using [annotations](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#annotations). This will only work with RAML 1.0 though.

**Comment by jpbelang** [comment]
2.x can do this through configuration.
