### ISSUE TITLE
 raml-jaxrs-maven-plugin: RAML to JAX-RS: provide option to allow plain JAX-RS Responses instead of generated Response types

### ISSUE THREAD

**Issue by Sevyls** [mulesoft-labs/raml-for-jax-rs#215]
Currently the maven plugin generates specific Response Types which allow easy use of the exact API. 
Adding undocumented (i.e. technical) attributes to an implementation becomes real hard.

i.e. RAML:

```yaml
/resources
  post: 
    responses:
      201: 
        ...
```

Generates the following JAX-RS interface:
```java
@Path("resources")
public interface ResourcesResource {
//...
public class PostResourcesResponse
        extends package.resource.support.ResponseWrapper
    {


        private PostResourcesResponse(Response delegate) {
            super(delegate);
        }
//...

```

and if you follow the generated Code you do something like this:

```java
public class ResourcesExampleResource implements ResourcesResource {
//...
public PostResourcesResponse postResources()  {
//...
return PostResourceResponse.withCreated();
}
```

Adding a header or some other HTTP Response related stuff, you will have to specify this in detail in your RAML.
(Implementation specific details, which do not reflect the base characteristics of a defined API like CORS, caching, etc.)

For this it could be useful to have an option to generate interface with the classic `javax.ws.rs.core.Response` in place, which would allow the usage of the generated Response classes but also ad-hoc Response class definitions. 

i.e. a switch in maven plugin configuration:
```xml
<useAbstractResponses>true</useAbstractResponses>
```

which would generate:

```java
public interface ResourcesResource {
//...
public Response postResources()  {
//...

```

**Comment by jstoiko** [comment]
hi @Sevyls, there is a [new version](https://github.com/mulesoft/raml-for-jax-rs/tree/release/2.0.0) in the works with RAML 1.0 support. 

If it's still relevant, would you mind trying to generate a response again using the new version?

```
$ git clone git@github.com:mulesoft/raml-for-jax-rs.git -b release/2.0.0
$ cd raml-for-jax-rs/
$ mvn clean install
```

**Comment by jpbelang** [comment]
in 2.x, could be done by plugins, I think.
