### ISSUE TITLE
Build JAXRS code generator standalone jar

### ISSUE THREAD

**Issue by cskradski** [mulesoft-labs/raml-for-jax-rs#219]
Can someone provide instructions for building the release 2.0.0 standalone code gen jar with dependencies included?  Thanks in advance!

**Comment by jstoiko** [comment]
@cskradski: we just added a separate package that builds a JAR with dependencies. 

Now you can do:
```
$ git clone git@github.com:mulesoft/raml-for-jax-rs.git -b release/2.0.0
$ cd raml-for-jax-rs/
$ mvn clean install
```

It automatically builds a `raml-to-jaxrs-cli-<version>-jar-with-dependencies.jar` JAR file inside the `raml-to-jaxrs/raml-to-jaxrs-cli/target/` folder.

Then you can do:
```
$ cd raml-to-jaxrs/
$ java -jar ./raml-to-jaxrs-cli/target/raml-to-jaxrs-cli-2.0.0-RC2-SNAPSHOT-jar-with-dependencies.jar -d /tmp -r foo.bar ./examples/maven-examples/raml-defined-example/src/main/resources/types_user_defined.raml
```

This generates a `foo.bar` package inside `/tmp` from the RAML file included in the `ramp-defined-example` example.

Hope this helps!

**Comment by cskradski** [comment]
Build failed with [ERROR] Plugin org.apache.maven.plugins:maven-source-plugin:2.3 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-source-plugin:jar:2.3: Could not transfer artifact org.apache.maven.plugins:maven-source-plugin:pom:2.3 from/to central (https://repo.maven.apache.org/maven2): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]

Is there a jar with dependencies available in a repository?

**Comment by jstoiko** [comment]
There will be as soon the GA is released which should happen in the next few days.

PS: after doing a quick "Google search", the error your getting seems to be linked to older Maven versions, which version are you using? have you tried updating Maven?

**Comment by jpbelang** [comment]
It should be in the repo now.
