### ISSUE TITLE
Generated POJO classes need to have serializable interface implemented 

### ISSUE THREAD

**Issue by raghucha** [mulesoft-labs/raml-for-jax-rs#220]
Hi , we have a requirement where in the POJO  generated  by the RAML  plugin need to have Serializable interface implemented as we are trying to save data in session . This is an enhancement request

**Comment by vijayrcse** [comment]
hi is there any update on this issue ?

**Comment by mplanchant** [comment]
Just add it to your JSON schema [https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference#javainterfaces](https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference#javainterfaces).

**Comment by vijayrcse** [comment]
thanks a lot @mplanchant , This works perfectly...

**Comment by vijayrcse** [comment]
Hi
Would like to know how this is supported in RAML 1.0 
We are using dataTypes in RAML 1.0 spec. how can we customize the type classes generated to have serilizable interface implemented 

Pls advise

**Comment by jpbelang** [comment]
@vijayrcse You could write a plugin to add the superinterface.

Check out the examples around 
raml-to-jaxrs/examples/maven-examples/features/feature-plugins/src/main/java/org/raml/jaxrs/features/AddDeprecatedAnnotationToTypePlugin.java

the code generation is handled by javapoet.  From memory, you could do something like
builder.addSuperInterface(ClassType.javaClass(Serializable.class));

Or something thereabouts.
