### ISSUE TITLE
Generating toString, hashCode and equals for Java classes generated from RAML DataTypes

### ISSUE THREAD

**Issue by mplanchant** [mulesoft-labs/raml-for-jax-rs#223]
It is possible to generate Java classes with toString, hashCode and equals methods from JSON schemas (described [here](https://github.com/mulesoft-labs/raml-for-jax-rs/tree/release/2.0.0/raml-to-jaxrs/examples/maven-examples/simple-json-example)). Is this possible when Java classes are generated from RAML DataTypes?

**Comment by jstoiko** [comment]
@mplanchant: you should be able to use RAML 1.0 annotations along with those [plugins](https://github.com/mulesoft-labs/raml-for-jax-rs/tree/release/2.0.0/raml-to-jaxrs/jaxrs-code-generator). I hope that helps.

**Comment by podviaznikov** [comment]
I think this one is important. Otherwise, those generated files need to be modified which defeats the purpose of generation a bit.

**Comment by jpbelang** [comment]
the raml-java-tools is coming with plugins to allow this

**Comment by jpbelang** [comment]
equals and hashCode are in for ObjectTypeDeclaration.  I'll do unions later today.

**Comment by jpbelang** [comment]
unions are done.  
The plugin can be set in the pom.xml or you can set it on the API of type directly (where you can specify a list of fields to consider field names.  I'll do toString() in a separate plugin.

**Comment by jpbelang** [comment]
toString plugin for types, called core.toString

**Comment by jstoiko** [comment]
FYI, those plugin options are documented here: https://github.com/mulesoft-labs/raml-java-tools/blob/19fe0a1b7e2dcbaa82a9d85eff57784f8db53779/raml-to-pojo/README.md
