### ISSUE TITLE
ConcurrentModificationException when using raml-to-jaxrs-cli

### ISSUE THREAD

**Issue by leflamm** [mulesoft-labs/raml-for-jax-rs#226]
Being on commit 56efb5c46578142148a4f096e5511b904b28074b (HEAD -> release/2.0.0, origin/release/2.0.0)
```raml
#%RAML 1.0
title: mini
version: v0.0.1

types:

  Method:
    enum: [POST, GET, PUT, PATCH, DELETE, OPTIONS, HEAD]

  ArticleReference:
    type: object
    properties:
      type:
        enum: [similar, accessories, others]
```

When trying to run `java -jar ./target/raml-to-jaxrs-cli-2.0.0-RC2-SNAPSHOT-jar-with-dependencies.jar -d /tmp -r com.foo mini.raml` the following exception is thrown

```java
Exception in thread "main" java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1466)
	at org.raml.jaxrs.generator.CurrentBuild.generate(CurrentBuild.java:115)
	at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:94)
	at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:74)
	at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:55)
	at org.raml.jaxrs.ramltojaxrs.Main.main(Main.java:75)
```

Deleting either declaration - `ArticleReference` or `Method` - will let the code generation run without errors.

**Comment by leflamm** [comment]
Problem is gone if you declare your enum types at top level.

**Comment by jpbelang** [comment]
I'll look into it tonight.  Pretty sure I know what it is.  The handling of internal types is a bit tricky.  Thanks for the example.

**Comment by leflamm** [comment]
Another twist: If you have a top level enum declaration of an enum type called `Foo` and you use that type to declare a property inside an object `bar: Foo` then the enum type `Foo` will be generated, but property is generated to be of type `Bar`! So...
- referenced type equals property/field name with first letter capitalized (in general this type doesn't exist)
- declared type is generated but never used
- workaround: follow the pattern "enum type name must be capitalized enum property/field name"

**Comment by jstoiko** [comment]
@leflamm: I think [this](https://github.com/mulesoft-labs/raml-for-jax-rs/commit/373ae1ab5cc032b7fba23f52ba69aa7942d96fbe) fixed the problem. right?

**Comment by leflamm** [comment]
Hi @jstoiko, this certainly prevents the `ConcurrentModificationException` - not sure what this means regarding correct behavior. Or does this also cover the mentioned "twist"? That I could check.

**Comment by jpbelang** [comment]
I think the twist was fixed.  Could you check ?
