### ISSUE TITLE
RAML to JAX-RS code gen not generating java.util.Long dataype

### ISSUE THREAD

**Issue by vijayrcse** [mulesoft-labs/raml-for-jax-rs#228]
Hi All,

is there a way to get Long dataype to be generated in the java code. For my RAML refering to the below schema it generates the datatype as Double ( for attribute "abc" )

{
     "$schema": "http://json-schema.org/draft-04/schema#",
     "type": "object",
     "description": "xyzSchema",
     "additionalProperties": false,
     "properties": {
           "abc": {
                "type": "number"
           },
     }
}

please advise

**Comment by jpbelang** [comment]
Are you using the 2.0.0 branch ?

**Comment by vijayrcse** [comment]
yes using 2.0.0-RC1

**Comment by jstoiko** [comment]
@vijayrcse: would you mind trying your RAML/JSON schema using the release/2.0.0 branch?

**Comment by vijayrcse** [comment]
can you please share the groupid, artifactid of that 2.0.0 branch plugin
please ?

**Comment by jstoiko** [comment]
```
$ git clone git@github.com:mulesoft/raml-for-jax-rs.git -b release/2.0.0
$ cd raml-for-jax-rs/
$ mvn clean install
```

This will build the JARs in the `target/` sub-folders of each project.
