### ISSUE TITLE
Question: What is @BuildType("ramlforjaxrs-simple") for

### ISSUE THREAD

**Issue by leflamm** [mulesoft-labs/raml-for-jax-rs#230]
Hi,

annotation seems to add an unnecessary(?) dependency to `org.raml:raml-for-jaxrs-common`. What is it for?

Thx, Christian

**Comment by jpbelang** [comment]
This code is in flux:  we are trying to find a way to control the way raml types are encoded from jaxrs types.
The name sure is crap though.

**Comment by jstoiko** [comment]
This has been removed and replaced by `@RamlGenerator()` annotations. Closing this issue.
