### ISSUE TITLE
Issue with generated class level @Path annotation

### ISSUE THREAD

**Issue by vijayrcse** [mulesoft-labs/raml-for-jax-rs#231]
I am using the RAML to JAX-RS code gen plugin where i am getting below source code generated

```java
@Path("/**resources**")
public interface Resources {
  @POST
  @Path("/**resources**/subresource")
  @Produces("application/json")
  PostResourcesSubresourceResponse postResourcesSubresource();
}
```

You can see here the "resources" from from RAML is generated at class level as well as method level.
Please advise if this can be fixed

RAML 1.0
-----------

```raml
 #%RAML 1.0
title: Template Services
version: v1
mediaType: application/json

/resources:
     /subresource: 
```

EDIT: description edited to add formatting to the Java and RAML snippets (by @jstoiko)

**Comment by vijayrcse** [comment]
hi any update on this ?

becoz @Path annotation appears at class level as well as method, the resource is accessible only as below

/resources/resources/subresource

Please advise if tis can be fixed

**Comment by jpbelang** [comment]
Yes it can, looking into it.

**Comment by jpbelang** [comment]
It's been fixed.  I've added a check in the type-torture-test (which I'll push  as soon as I get my permissions back).

Tell me if it works.

**Comment by vijayrcse** [comment]
sure will test today and let you know

**Comment by vijayrcse** [comment]
tested in snapshot. working fine
