### ISSUE TITLE
leading underscores are thrown away

### ISSUE THREAD

**Issue by leflamm** [mulesoft-labs/raml-for-jax-rs#233]
Hi!
```raml
#%RAML 1.0
title: mini
version: v0.0.1

types:

  Foo:
    type: object
    properties:
      _bar: string
```
Generated Java code
```bash
$ find model/
model/
model/FooImpl.java
model/Foo.java
```
```java
package model;

import java.lang.String;
import org.raml.jaxrs.common.BuildType;

@BuildType("ramlforjaxrs-simple")
public interface Foo {
  String getBar();

  void setBar(String bar);
}
```
```java
package model;

import java.lang.String;

public class FooImpl implements Foo {
  private String bar;

  public String getBar() {
    return this.bar;
  }

  public void setBar(String bar) {
    this.bar = bar;
  }
}
```
We need this for e. g. `_schema` and `_links` information.

Thx, Christian.

**Comment by jpbelang** [comment]
I've fixed this by allowing _variables_ to lead with an underscore.

**Comment by leflamm** [comment]
It seems that this doesn't help - I'm getting this generated code:
```
  public Schema getSchema() {
    return this._schema;
  }
```

We're using 2.1.0.

I'm not sure if "get_schema" would be a nice name for the getter (and if this conforms to the Beans standard), one solution would be to add a JsonProperty annotation:

```
  @JsonProperty("_schema")
  public Schema getSchema() {
    return this._schema;
  }
```

But the danger here is that you get a clash, in case somebody has two attributes "_schema" and "schema". But in that case, the generator could just throw an exception (in case get_schema() is not an option).

**Comment by leflamm** [comment]
@jstoiko or @jpbelang 

Could you please reopen this issue?

**Comment by jpbelang** [comment]
Hi

I ran with the current code (which has changed a lot).  We currently generate:
```java
public interface Foo {
  Map<String, Object> getAdditionalProperties();

  void setAdditionalProperties(Map<String, Object> additionalProperties);

  @JsonProperty("_bar")
  String getBar();

  @JsonProperty("_bar")
  void setBar(String _bar);
}
```

Could you check ? On release/2.2.0 ?

Don't forget to add
```xml
                    <generateTypesWith>
                        <value>jackson</value>
                    </generateTypesWith>
```

**Comment by leflamm** [comment]
```xml
<generateTypesWith>
  <value>jackson</value>
</generateTypesWith>
```
Does the job! Thx
