### ISSUE TITLE
Is 2.0 released or not?

### ISSUE THREAD

**Issue by wwulfric** [mulesoft-labs/raml-for-jax-rs#235]
I try to use it like https://github.com/mulesoft-labs/raml-for-jax-rs/blob/release/2.0.0/jaxrs-to-raml/jaxrs-test-resources/pom.xml, but I cannot download it. I checked it in https://repository-master.mulesoft.org/nexus/content/repositories/releases/ and https://repository-master.mulesoft.org/nexus/content/repositories/snapshots/ and didn't find 2.0.

**Comment by jstoiko** [comment]
`2.0.0-RC1` is [here](https://repository-master.mulesoft.org/nexus/content/repositories/releases/org/raml/jaxrs-to-raml/2.0.0-RC1/).

If you're trying that example from the repo, you might be better off building directly in that folder with `mvn clean install`.

**Comment by PascalBru** [comment]
Will release 2.0.0 also published at Maven Central Repository?

**Comment by jstoiko** [comment]
@PascalBru: https://github.com/mulesoft-labs/raml-for-jax-rs/blob/master/README.md#maven-artifacts

**Comment by jstoiko** [comment]
@PascalBru FYI, release 2.1.0 is now on Maven Central: http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.raml.jaxrs%22
