### ISSUE TITLE
raml-jaxrs-maven-plugin 1.3.4 not supporting raml 1.0 

### ISSUE THREAD

**Issue by paulprashant1510** [mulesoft-labs/raml-for-jax-rs#236]
Hi,
I am using raml 1.0, I want to generate resources using raml-jaxrs-maven-plugin 1.3.4.
Can someone please tell me is this possible because I am getting multiple errors saying "Error Unknown Key:" for attributes like description, traits, type.

**Comment by jstoiko** [comment]
1.3.x only supports RAML 0.8. For RAML 1.0 support, you can use the 2.0.0-RC1 version from the maven repository. The 2.0.0-GA will be released very soon (in the next few days). In the meantime, if you want to try the latest features (built after RC1), you can follow [these steps](https://github.com/mulesoft-labs/raml-for-jax-rs/issues/228#issuecomment-292621330). Hope this helps!

**Comment by paulprashant1510** [comment]
@jstoiko thanks for sharing the information.. It's very helpful
