### ISSUE TITLE
eclipse plugin generation - raml-to-jax-rs

### ISSUE THREAD

**Issue by vijayrcse** [mulesoft-labs/raml-for-jax-rs#238]
Like maven plugin is there a way to generate sources using eclipse plugin ? is this supported ?
( raml-for-jaxrs 1.3.4 supported eclipse plugin )

Please advise.

**Comment by jstoiko** [comment]
it's been dropped in 2.0.0 release in favor of maven/CLI. 

moving the discussion [here](https://github.com/mulesoft-labs/raml-for-jax-rs/issues/240).
