### ISSUE TITLE
Unable to build maven plugin

### ISSUE THREAD

**Issue by tkhosravi** [mulesoft-labs/raml-for-jax-rs#24]
Hi,
I am trying to use the maven in order to generate jax-rs interface within maven build. I've followed your instructions: https://github.com/mulesoft/raml-for-jax-rs/blob/master/maven-plugin.md
However, I cannot install the maven-plugin module. I have the following output:

$ mvn install
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building RAML JAX-RS Maven Plug-in 1.0.6-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.637s
[INFO] Finished at: Mon Dec 08 14:09:12 CET 2014
[INFO] Final Memory: 5M/20M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project raml-jaxrs-maven-plugin: Could not resolve dependencies for project org.raml.plugins:raml-jaxrs-maven-plugin:maven-plugin:1.0.6-SNAPSHOT: Failed to collect dependencies for [org.raml:raml-jaxrs-codegen-core:jar:1.0.6-SNAPSHOT (compile), org.apache.maven.plugin-tools:maven-plugin-tools-api:jar:3.2 (compile), org.apache.maven.plugin-tools:maven-plugin-tools-annotations:jar:3.2 (compile)]: Failed to read artifact descriptor for org.raml:raml-jaxrs-codegen-core:jar:1.0.6-SNAPSHOT: Failure to find org.raml:raml-jaxrs-codegen-parent:pom:1.0.6-SNAPSHOT in https://repository.mulesoft.org/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of mulesoft-snapshots has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

It seems that this dependency is not available anymore.

Thanks in advance.

**Comment by gertvs** [comment]
I am having the same issue, this time with version 1.3.2-SNAPSHOT:
[ERROR] Failed to execute goal on project raml-jaxrs-maven-plugin: Could not resolve dependencies for project org.raml.plugins:raml-jaxrs-maven-plugin:maven-plugin:1.3.2-SNAPSHOT: Failed to collect dependencies at org.raml:raml-jaxrs-codegen-core:jar:1.3.2-SNAPSHOT: Failed to read artifact descriptor for org.raml:raml-jaxrs-codegen-core:jar:1.3.2-SNAPSHOT: Could not find artifact org.raml:raml-jaxrs-codegen-parent:pom:1.3.2-SNAPSHOT in mulesoft-snapshots (https://repository.mulesoft.org/snapshots/) -> [Help 1]

I tried to follow the JIRA link above, but am prompted to log in, which I can't.

**Comment by wvdhaute** [comment]
Same issue with v1.3.2. Still not all necessary artifacts are available in the repository.

**Comment by wvdhaute** [comment]
Same issue with v1.3.3, not all transitive dependencies are available: raml-parser-0.9-20150218.154027-76

**Comment by dmiorandi** [comment]
Snapshot version work for me ....

```xml

			<plugin>
				<groupId>org.raml.plugins</groupId>
				<artifactId>raml-jaxrs-maven-plugin</artifactId>
				<version>1.3.4-SNAPSHOT</version>
				<configuration>
					<!-- Use sourcePaths if you want to provide a single RAML file or a 
						list of RAML files -->
					<sourceDirectory>${basedir}/src/main/resources/api</sourceDirectory>
					<!-- Optionally configure outputDirectory if you don't like the default 
						value: ${project.build.directory}/generated-sources/raml-JAX-RS -->
					<!-- Replace with your package name -->
					<basePackageName>it.clesius.resources.ams</basePackageName>
					<!-- Valid values: 1.1 2.0 -->
					<useJsr303Annotations>true</useJsr303Annotations>
					<!-- Valid values: jackson1 jackson2 gson none -->
					<jsonMapper>jackson2</jsonMapper>
					<removeOldOutput>false</removeOldOutput>
					<outputDirectory>${basedir}/src/main/generated</outputDirectory>
					<jaxrsVersion>2.0</jaxrsVersion>
					<!-- Optionally set extensions to a list of fully qualified names of 
						classes that implement org.raml.jaxrs.codegen.core.ext.GeneratorExtension -->
					<!-- for example: <extensions> <param>com.abc.AuthorizationAnnotationExtension</param> 
						<param>com.abc.ParameterFilterExtension</param> </extensions> Custom annotator 
						for json schema to pojo convertor <customAnnotator>com.abc.MyCustomAnnotator</customAnnotator> -->
					<jsonMapperConfiguration>
						<useLongIntegers>true</useLongIntegers>
						<useJodaDates>true</useJodaDates>
						<useJodaLocalDates>true</useJodaLocalDates>
						<useJodaLocalTime>true</useJodaLocalTime>
					</jsonMapperConfiguration>
				</configuration>
				<executions>
					<execution>
						<id>raml-jaxrs</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<phase />
					</execution>
				</executions>
				<dependencies>
					<!-- <dependency> -->
					<!-- <groupId>org.jsonschema2pojo</groupId> -->
					<!-- <artifactId>jsonschema2pojo-core</artifactId> -->
					<!-- <version>0.4.15</version> -->
					<!-- </dependency> -->
					<dependency>
						<groupId>org.raml</groupId>
						<artifactId>raml-jaxrs-codegen-core</artifactId>
						<version>1.3.4-SNAPSHOT</version>
						<!-- <exclusions> -->
						<!-- <exclusion> -->
						<!-- <groupId>org.jsonschema2pojo</groupId> -->
						<!-- <artifactId>jsonschema2pojo-core</artifactId> -->
						<!-- </exclusion> -->
						<!-- </exclusions> -->
					</dependency>
					<dependency>
						<groupId>com.fasterxml.jackson.datatype</groupId>
						<artifactId>jackson-datatype-jsr310</artifactId>
						<version>2.6.3</version>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
```

**Comment by wvdhaute** [comment]
The maven-deploy-plugin fails also on that version:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7-7l:find-and-deploy (default-cli) on project incoming-dependencies: 1 problem was encountered while building the effective model for org.raml:raml-jaxrs-codegen-core:1.3.4-SNAPSHOT
[ERROR] [FATAL] Non-resolvable parent POM: Could not find artifact org.raml:raml-jaxrs-codegen-parent:pom:1.3.4-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 11
[ERROR] for project org.raml:raml-jaxrs-codegen-core:1.3.4-SNAPSHOT at /var/folders/pz/r4fwvj_14ps430m5fy2k64gr0000gn/T/deploy-plugin5717761575642369132pom

**Comment by wvdhaute** [comment]
But 1.3.4-SNAPSHOT does indeed work if I add the mulesoft repos in my project next to my own central repo.
