### ISSUE TITLE
CLI ignores generate-types-with parameter

### ISSUE THREAD

**Issue by tomzo** [mulesoft-labs/raml-for-jax-rs#242]
I just tried running `2.0.0`, the generated model types are never annotated with anything. Regardless of `-g jackson` parameter I pass.
I think there was a bug introduced in this commit https://github.com/mulesoft-labs/raml-for-jax-rs/commit/0d6e4a9a7eb476d1bbc0fb8d9450456073651abf

Shouldn't something like `configuration.setJsonMapper` be called somewhere around [here](https://github.com/mulesoft-labs/raml-for-jax-rs/blob/master/raml-to-jaxrs/raml-to-jaxrs-cli/src/main/java/org/raml/jaxrs/ramltojaxrs/Main.java#L65)

My full command was
```
java -jar /ide/work/raml-for-jax-rs/raml-to-jaxrs/raml-to-jaxrs-cli/target/raml-to-jaxrs-cli-2.0.0-jar-with-dependencies.jar  -d /ide/work/spike-raml/example/src/main/java/ -g jackson -m model -r api -s support /ide/work/spike-raml/spike.raml
```

**Comment by jpbelang** [comment]
Sorry, missed your report.  Fixed.  Just bad parsing.
