### ISSUE TITLE
Client ( RESTful service consumer ) usage of codegen - raml-to-jaxrs

### ISSUE THREAD

**Issue by vijayrcse** [mulesoft-labs/raml-for-jax-rs#244]
Hi
We have a service implementation and RAML spec for that.

Can we give the RAML spec to our Client ( RESTful service consumer )  and ask them to use "raml-to-jaxrs" code gen ?

What is the best guideline here for the client code generation ?

**Comment by jstoiko** [comment]
@vijayrcse: is this version

**Comment by rreddy2014** [comment]
Hi @vijayrcse , how did you solve this issues regarding Restful service consumer , I have the same issue .  I have a RAML 1.0(does not have Jsonschema insted data types ) spec and Would like to give it to  client to use it to generate client code .

THanks in advance

**Comment by vijayrcse** [comment]
Hi rreddy2014
We used raml-to-jaxrs code gen. But for service consumer it is still unclear how the generated sources should be used.
For now the client take the RAML 1.0 spec, generate the sources but only use the model objects. We use JAX RS client API at service consumer

<jaxrs:client id="restClient"
       address="http://localhost:${testutil.ports.BookServerRestSoap}/test/services/rest"
       serviceClass="org.apache.cxf.systest.jaxrs.BookStoreJaxrsJaxws"
       inheritHeaders="false">
      
</jaxrs:client>

**Comment by rreddy2014** [comment]
Thanks alot @vijayrcse   for quick replay. I will also try the same, but how are they validating consuming JSON data.

Thanks in advance.

**Comment by vijayrcse** [comment]
To my knowledge you don't get anything generated by the plugin for response validation. You might have to look for your own  implementation or any solution

**Comment by rreddy2014** [comment]
Thnaks @vijayrcse
