### ISSUE TITLE
Generating Jackson Annotations for RAML 1.0 types

### ISSUE THREAD

**Issue by KevinMitchell** [mulesoft-labs/raml-for-jax-rs#250]
Hi,  
I'm trying to use raml-to-jaxrs with a RAML 1.0 spec with RAML 1.0 types.  The POJOs for the types are generated OK.  But they don't have any Jackson annotations attached to them.  Is this a configuration problem on my side, or are these annotations currently only generated if I start with Json schemas for the types, rather than RAML types?

The configuration part of my pom.xml file looks like this:
```
<configuration>
  ...
  <jsonMapper>jackson2</jsonMapper>
  <jsonMapperConfiguration>
    <annotationStyle>jackson2></annotationStyle>
  </jsonMapperConfiguration>
</configuration>
```
Thanks,
Kevin

**Comment by jstoiko** [comment]
Hi @KevinMitchell, are you using the CLI or the Maven Plugin? For the CLI, there is an [optional `-g` argument that needs to be passed](https://github.com/mulesoft-labs/raml-for-jax-rs/blob/master/raml-to-jaxrs/README.md#using-the-cli). For the Maven plugin, it's the [`<generateTypesWith>` option in your POM](https://github.com/mulesoft-labs/raml-for-jax-rs/blob/master/raml-to-jaxrs/examples/maven-examples/raml-defined-example/pom.xml#L50-L52). I hope this is helpful.

**Comment by KevinMitchell** [comment]
Thanks for the hint.  The option, plus upgrading to the latest version, produced the annotations.

Thanks.
