### ISSUE TITLE
Missing intermediate paths

### ISSUE THREAD

**Issue by b0bd** [mulesoft-labs/raml-for-jax-rs#252]
Using the following raml snippet with 2.0.1-SNAPSHOT I get "/Attachments" in the generated class instead of "{viewingSessionId}/Attachments": Playing with the RAML it seems I'm only getting the first part of the URL on the interface class and the final part on the method, but the intermediate parts are dropped.

raml fragment:
```
/ViewingSession:
  /{viewingSessionId}:
    /Attachments:
      uriParameters:
        viewingSessionId:
          type: string
      get:
        responses:
          200:
            body:
              application/json:
                type: EmptyObject
```

generated java fragment:

```
@Path("/ViewingSession")
public interface ViewingSession {
  @GET
  @Path("/Attachments")
  @Produces("application/json")
  GetViewingSessionAttachmentsByViewingSessionIdResponse getViewingSessionAttachmentsByViewingSessionId(@PathParam("viewingSessionId") String viewingSessionId);
```

**Comment by KevinMitchell** [comment]
We've got the same problem, and it's show-stopper for us.  We are exposing the wrong paths and have no access to the URI parameter.  Is this a problem with just the latest release, and downgrading to an earlier release will fix it.  Or has this always been broken?  Is there an ETA for a fix?

**Comment by jpbelang** [comment]
Looking at it.

**Comment by jpbelang** [comment]
Seems I don't check the "intermediate paths" correctly.  
I'm working on something, but in the meantime, could you
 
```
/ViewingSession:
  /{viewingSessionId}/Attachments:
      uriParameters:
        viewingSessionId:
          type: string
      get:
        responses:
          200:
            body:
              application/json:
                type: string
```

**Comment by jpbelang** [comment]
Just pushed a fix, with a UT and added to the torture test.

Feedback por favor ?

**Comment by KevinMitchell** [comment]
Still not quite right.  Suppose I define
```
/a:
  /{b}:
    uriParameters:
      b: integer
    /c:
      get:
```
The tool generates
```
@Path("/a")
public interface A {
  @GET
  @Path("/{b}/c")
  void getAC();
}
```
So the method `getAC` is missing the URI parameter.

**Comment by jpbelang** [comment]
I'll look at it today.  I thought the parser would handle stuff like this...

**Comment by KevinMitchell** [comment]
But you are generating the declaration of getAC aren't you?  And presumably what you generate for that needs to include the declaration of `@PathParam("b") Integer b)` as arguments.  The parser just provides the model, so you can access the URI/path parameters from it.  

Are you also planning on allowing the methods to return an instance of `Response` rather than just `void`?

**Comment by jpbelang** [comment]
@KevinMitchell Yes, but it does some things to help you, and not others:  I'll have to go fetch PathParams from the parent resources.  

As to the second question, I'm not sure I get what you are saying:  we do return a response.  Which case are you talking about ?

**Comment by KevinMitchell** [comment]
Yes, you are correct.  It was me getting confused on this occasion.  I tried to make the example as simple as possible, but it ended up being too simple, had left out the response code, and so you quite correctly didn't generate anything.  So ignore that bit :-)

So it's just the path param we are missing.

Thanks,
Kevin

**Comment by jpbelang** [comment]
Check again when you have time please.

**Comment by KevinMitchell** [comment]
That looks better.  Thanks for the prompt response.

**Comment by jpbelang** [comment]
Good.  Closing.   If something else comes up, ping!
