### ISSUE TITLE
Wrong generated type for enum references

### ISSUE THREAD

**Issue by KevinMitchell** [mulesoft-labs/raml-for-jax-rs#254]
The code generator seems to construct the wrong type for enum references.

Consider this example:
```
#%RAML 1.0
title: New API
version: v1
baseUri: http://api.samplehost.com
types:
  TestFrequency:
    enum: [annually, semi-annually, quarterly, monthly]
 
  TestType:
    type: object
    properties:
      id: number
      frequency?: TestFrequency

/helloWorld:
  get:
    responses:
      200:
        body:
          application/json:
            type: TestType
```
This results in the following code being generated:
```
public class TestTypeImpl implements TestType {
  ...
  @JsonProperty("frequency")
  private Frequency frequency; 
  ...
```
The variable `frequency` should be declared to have type TestFrequency not Frequency.

**Comment by jpbelang** [comment]
Fixed.  I really don't like my type management....

**Comment by KevinMitchell** [comment]
Thanks.  I'll try it out.  And I share your pain about type management; I've made similar mistakes in the past :-)
