### ISSUE TITLE
Primitive types not usable in arrays

### ISSUE THREAD

**Issue by adjokic** [mulesoft-labs/raml-for-jax-rs#255]
Hello,
I was defining a simple object type which contains an integer[]:
```
#%RAML 1.0 DataType

type: object
properties:
  integers: integer[]
```
which results in an exception from the JavaPoet library:
```
java.lang.IllegalArgumentException: invalid type parameter: long
	at com.squareup.javapoet.Util.checkArgument(Util.java:64)
	at com.squareup.javapoet.ParameterizedTypeName.<init>(ParameterizedTypeName.java:51)
	at com.squareup.javapoet.ParameterizedTypeName.<init>(ParameterizedTypeName.java:38)
	at com.squareup.javapoet.ParameterizedTypeName.get(ParameterizedTypeName.java:111)
	at org.raml.jaxrs.generator.v10.types.V10GTypeArray.defaultJavaTypeName(V10GTypeArray.java:75)
```

the solution is very simple by changing the following in V10GTypeArray.defaultJavaTypeName():
```
    return ParameterizedTypeName.get(
                                     ClassName.get(List.class),
                                     arrayContents().defaultJavaTypeName(pack).box());
```
we need to box any potential primitive which we want to use as a parameter type in a List.

I haven't tested this fully, but I think we'd still need to write a few test cases: creating RAML types with arrays for all Java primitive types, custom defined objects, and object[]

**Comment by jpbelang** [comment]
I'm looking into it.  I suspect something stupid (on my part)

**Comment by jpbelang** [comment]
Not as stupid as I thought, but stupid nonetheless.  Fix incoming tonight.

**Comment by jpbelang** [comment]
Fixed, please check.

I didn't box the types in array types. And my only scalar test was on the raml string type.

**Comment by adjokic** [comment]
just tested it and it is working for me. thank you!
