### ISSUE TITLE
RAML validation fails with ":" in description

### ISSUE THREAD

**Issue by kumaranae** [mulesoft-labs/raml-for-jax-rs#258]
Hi Team,

we have a JaxRS API with documentation that contains ":" in it, like "HH:MM:SS". Once we generated a RAML file using Maven plugin, i tried to validate the RAML file using online validation tools. Its fails saying error as below,

Underlying error while parsing YAML syntax: 'mapping values are not allowed here in 'reader', line 126, column 41: ... description: cancels the job: stops the job's execution and ... ^ 

If am correct, the description should be closed with double quote which will escape the ":" character.

Regards,
Kumaran.A.E

**Comment by jpbelang** [comment]
Ok, know where that is.  Will fix in the week-end.

**Comment by jpbelang** [comment]
I did a fairly narrow fix:  if a line ends with a ":", I quote.  Is this your use case ?

**Comment by kumaranae** [comment]
Below snippet from my RAML,

/firmwareUpgradeBatch/{batchName}/cancel:
        post:
            description: cancels the job: stops the job's execution and sets its status to canceled

**Comment by jpbelang** [comment]
My mistake:  it's not just ending.  it's ": ".  I'll make it more general.

Thanks.

**Comment by jpbelang** [comment]
Try it again.  Thanks for your input, BTW.

**Comment by kumaranae** [comment]
Hi.

This changed worked as expected. thanks for your quick response. Please let me know once you merged it.

**Comment by jpbelang** [comment]
It should be merged end of May (for 2.0.1).

**Comment by kumaranae** [comment]
Hi,

Where can i find this fix?

**Comment by jpbelang** [comment]
Right now only in 2.0.1 branch.
