### ISSUE TITLE
Regular expression in @PATH fails

### ISSUE THREAD

**Issue by kumaranae** [mulesoft-labs/raml-for-jax-rs#259]
Hi Team,

Below my scenario where the @PATH as regular expression in it.

/household/{householdId}/devices/{devicesIds:.+}

Its perfectly converted into the RAML file. But when i tried to validate, it throws error in this path saying invalid syntax.
Do we need to update this regular expression?

**Comment by jpbelang** [comment]
What do you mean by "validate" ?  It parses correctly, correct ? 

RAML uses ECMA regexp, and java doesn't :-)

**Comment by kumaranae** [comment]
Am using an online RAML parsing tool https://studio.restlet.com for parsing and validating. It throws error saying invalid syntax. please correct me if am wrong. attaching screenshot for your reference.
<img width="1436" alt="screen shot 2017-05-22 at 11 34 48 am" src="https://cloud.githubusercontent.com/assets/5084408/26323207/d72d8462-3ee2-11e7-8b68-fd650bf17a53.png">

**Comment by jpbelang** [comment]
This is probably a bug in the studio.  Jaxrs likes it.
