### ISSUE TITLE
UnionDeserializationGenerator creates inconsistent "looksLike" method names

### ISSUE THREAD

**Issue by adjokic** [mulesoft-labs/raml-for-jax-rs#262]
Hello,
when a typeDeclaration.name() starts with a lowercase letter, the generated "looksLike" method name is transformed in `UnionDeserializationGenerator.buildLooksLike()` to camel case with the call `Names.methodName("looksLike", typeDeclaration.name());`

However, when generating the code that calls the "looksLike" methods, it is not transformed into camel case. I fixed this by changing UnionDeserializationGenerator:95 to be consistent with the above call:
```
      String name = Names.methodName("looksLike", typeDeclaration.name());
      deserialize.addStatement("if ( " + name + "(map) ) return new $T(mapper.convertValue(map, $T.class))",
                               unionTypeName, unionPossibility);
```

**Comment by jpbelang** [comment]
Thanks:  tomorrow, i'll apply your fix.
