### ISSUE TITLE
JAX RS Codegen is not generating the setter for AdditionalProperties 

### ISSUE THREAD

**Issue by jvenki** [mulesoft-labs/raml-for-jax-rs#263]
I am using RAML 1.0 and using 2.0.0 version of the Maven Plugin to generate JAXRS code from the RAML files. Looks like the code gen is not honouring the definition of https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#additional-properties. I dont see the generated Java files to have anything related to Additional Properties which used to happen with RAML 0.8 and 1.3.4 of this plugin. Can you please shed some light on this feature and whether it is supported or not?

**Comment by jpbelang** [comment]
The problem I have with additional properties is that it translates badly to XML (or other formats).  JSON, sure:  1.3 got that in jsonschema2pojo.

We replicate that (I'm pretty sure) when you generate JSON objects.

**Comment by jvenki** [comment]
If I use jsonMapper as Jackson2 alone, it is not generating anything. However, if I set generateTypesWith as jackson, then it generates the additionalProperties related logic. 

                  <jsonMapper>jackson2</jsonMapper>
                    <generateTypesWith>
                        <param>jackson</param>
                    </generateTypesWith>

**Comment by jvenki** [comment]
I am curious to understand on why we generate the *interfaces* for Model Classes. What is the value add. I understand the value of *design to interfaces*, but what is the great value add of generating interfaces for the model classes? If we are doing it, shouldnt the codegen automatically generate it with Jackson annotations too without the need for generateTypesWith. Otherwise, the deserialization wont work.

**Comment by jpbelang** [comment]
@jvenki Multiple inheritance, basically.  There are two ways to do this:  with interfaces or some sort of mixin support.  If you aren't using MI, then I agree that his is overhead.  On a positive note,  mixins, simple inheritance (and even no inheritance) are planned.

Also, REST apis also can support other formats:  gson, jackson, xml....

**Comment by jvenki** [comment]
Super. Eagerly waiting for those configurations so that I can disable them. Thanks for your help. Closing this.
