### ISSUE TITLE
Duplicate Definitions added to the Resource Interface if there are multiple end points with the same return type

### ISSUE THREAD

**Issue by jvenki** [mulesoft-labs/raml-for-jax-rs#264]
Thanks for your great support in creating the JAX RS code generations for RAML.

If I have two end points for an API and both the end points returns the same type of resource, the codegen creates two Response Type classes of the same name and thus the Java code is invalid. 

We generally have an API (A_ID) to get by ID and this always returns a single resource of type (T1). Because of some reason, I have another API (B_QUERYPARAMS) which takes in query parameters but will always return a  single resource (T1). Note that this is not a collection rather a single item. If I run the codegen, it generates two classes in the Resource's Interface as GetT1Response. 

Is there a way I can fix this in RAML or through some config setting.

**Comment by jpbelang** [comment]
I think I understand this.  Could you give me an example of your RAML so that I add it to our testing ?  This sounds like a bug.  just so I understand, two methods in one java file that return the same response code (200, I imagine), and ramlforjaxrs generates two identical classes for the response type.  Correct ?

Maybe a quick workaround:  every top resource generates a separate java file.  Could you place them in separate toplevel resources ?

/resource/one:
/resource/onewithqueryparam:

(along those lines, I'm at work right now, this is from the top of my head).

**Comment by jpbelang** [comment]
Something like this ?
```raml
/tracks:
    description: The search resource
    get:
        responses:
            200:
                body:
                    application/json:
                        type: Track
    put:
        body:
            application/json:
                type: Track
    /tooById:
        get:
            responses:
                200:
                    body:
                        application/json:
                            type: Track
    /too/{id}:
        uriParameters:
            Id: string
        get:
            responses:
                200:
                    body:
                        application/json:
                            type: Track
```

**Comment by giacgbj** [comment]
Same error using:

```
/foo:
  post:
    body:
      application/json:
        type: A
    responses:
      200:
        body:
          application/json:
            type: B

  /{bar}:
    post:
      body:
        application/json:
          type: C
      responses:
        200:
          body:
            application/json:
              type: D
```

The result is
```
public interface Foo {

   // This class twice! :-)
   class PostFooResponse extends ResponseDelegate {
     [...]
   } 

}
```

**Comment by jpbelang** [comment]
@giacgbj You don't seem to have a URI parameter even though you seem to have one in the URI.  If you add the parameter, it should work.

**Comment by giacgbj** [comment]
@jpbelang But I don't need a parameter.
The calls are:
* a POST to /foo
* a POST to /foo/{bar}

**Comment by jpbelang** [comment]
I have a regular expression that explicitly removes these when there are no parameters.  I'll have a look at why I added this. 

That being said, check out the jax-rs spec:  what you are doing seems to be incorrect (section 3.4) of http://download.oracle.com/otn-pub/jcp/jaxrs-2_0_rev_A-mrel-eval-spec/jsr339-jaxrs-2.0-final-spec.pdf?AuthParam=1497874622_0a269c3bcc89e105662be5e55675396c

`
Note: Because ‘{’and ‘}’ are not part of either the reserved or unreserved productions of URI[5] they will
not appear in a valid URI.
`

Seems you should be using %7B and %7D.

**Comment by giacgbj** [comment]
@jpbelang I don't want to use curly braces in the URI, but that's the RAML 1.0 syntax.

My example is equivalent to https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#template-uris-and-uri-parameters where "foo" is "jobs" and "bar" is "jobId".

So I'd expect the class created would be PostFooResponse and PostFooBarResponse.

**Comment by vivekshabadi** [comment]
Hi,
Am facing similar issue and i tried using the latest 3.0.0 version of the maven plugin, but it fails while downloading the dependent jars.  Please see below for the error message:

Downloading: https://repository-master.mulesoft.org/releases/org/raml/raml-to-pojo/1.0.0-SNAPSHOT/maven-metadata.xml
Downloading: http://rms-in.blr.mspu.hq.k.grp:8081/nexus/content/groups/mspu-public-in/org/raml/raml-to-pojo/1.0.0-SNAPSHOT/maven-metadata.xml
Downloading: https://repository-master.mulesoft.org/snapshots/org/raml/raml-to-pojo/1.0.0-SNAPSHOT/maven-metadata.xml
Downloading: http://rms-in.blr.mspu.hq.k.grp:8081/nexus/content/groups/mspu-public-in/org/raml/raml-to-pojo/1.0.0-SNAPSHOT/raml-to-pojo-1.0.0-SNAPSHOT.pom
Downloading: https://repository-master.mulesoft.org/releases/org/raml/raml-to-pojo/1.0.0-SNAPSHOT/raml-to-pojo-1.0.0-SNAPSHOT.pom
Downloading: https://repository-master.mulesoft.org/snapshots/org/raml/raml-to-pojo/1.0.0-SNAPSHOT/raml-to-pojo-1.0.0-SNAPSHOT.pom
[WARNING] The POM for org.raml:raml-to-pojo:jar:1.0.0-SNAPSHOT is missing, no dependency information available
Downloading: http://rms-in.blr.mspu.hq.k.grp:8081/nexus/content/groups/mspu-public-in/org/raml/raml-to-pojo/1.0.0-SNAPSHOT/raml-to-pojo-1.0.0-SNAPSHOT.jar
Downloading: https://repository-master.mulesoft.org/releases/org/raml/raml-to-pojo/1.0.0-SNAPSHOT/raml-to-pojo-1.0.0-SNAPSHOT.jar
Downloading: https://repository-master.mulesoft.org/snapshots/org/raml/raml-to-pojo/1.0.0-SNAPSHOT/raml-to-pojo-1.0.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.931 s
[INFO] Finished at: 2018-03-23T11:37:00+05:30
[INFO] Final Memory: 15M/211M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.raml.jaxrs:raml-to-jaxrs-maven-plugin:3.0.0:generate (GenerateAdminV1) on project ml-sp-bcm-api: Execution GenerateAdminV1 of goal org.raml.jaxrs:raml-to-jaxrs-maven-plugin:3.0.0:generate failed: Plugin org.raml.jaxrs:raml-to-jaxrs-maven-plugin:3.0.0 or one of its dependencies could not be resolved: Could not find artifact org.raml:raml-to-pojo:jar:1.0.0-SNAPSHOT in mspu-repo-in (http://rms-in.blr.mspu.hq.k.grp:8081/nexus/content/groups/mspu-public-in) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
