### ISSUE TITLE
General question on JAX_RS code gen for RAML 1.0 spec

### ISSUE THREAD

**Issue by vijayrcse** [mulesoft-labs/raml-for-jax-rs#266]
Hi All,

Would like to understand what is the stable release for this tool that we can use ?( is it 2.0.0-RC1)

When does the next stable release cut is expected ?

How much of RAML 1.0 support is covered   ? Can we depend on this tool for generating JAX-RS code based on RAML 1.0 API contracts ?

Thanks
-Vijay

**Comment by jpbelang** [comment]
Hi,
The current stable release 2.0.0 is on master.  2.0.1 branch is bugfixes and a few features.  It should be released beginning of June.

The objective is to cover as much as possible of 1.0, so anything you might find that isn't done you could mention.  Right now, we have basic types, objects and basic inheritance.  Unions are a work in progress:  the basics are there.  Inheriting from arrays isn't done yes.

As to the serialization, we are currently concentrating more on jackson2, followed by jaxb (although jaxb is more complicated, as always).

**Comment by vijayrcse** [comment]
Thanks a lot for the response. this helps
