### ISSUE TITLE
Patterns of created java classes ß how does it work??

### ISSUE THREAD

**Issue by TheOneAndOnlyAndreKempe** [mulesoft-labs/raml-for-jax-rs#267]
Hej guys,

I'm trying to understand the raml-for-jax-rs example projects and building an own sample projects. At this I ran into an issue with the patterns used in the created java implementation which can also be seen in the example projects (simple-json-example vs type-torture-test).

What I'm basically trying to achive is create the API for an WildflySwarm-Application from RAML.

With this RAML-Description [example_json_schema_raml.txt](https://github.com/mulesoft-labs/raml-for-jax-rs/files/1041351/example_json_schema_raml.txt) for the given ConfigExchangable an interface as well as an implementation is created, see [ConfigExchangableImp_java.txt](https://github.com/mulesoft-labs/raml-for-jax-rs/files/1041375/ConfigExchangableImp_java.txt) and
[ConfigExchangable_java.txt](https://github.com/mulesoft-labs/raml-for-jax-rs/files/1041376/ConfigExchangable_java.txt). However none of them has any Jackson annotation. Since DebugConfig-interface uses the interface of the body, when I call the request I get an error that no instance of ConfigExchangable can be created.

However, with this RAML-File [the_good_example_json_schema_raml.txt](https://github.com/mulesoft-labs/raml-for-jax-rs/files/1041395/the_good_example_json_schema_raml.txt) no interface but only an implementation is created, it employs @JSONXXX annotation and works.

From my understanding, both RAML-files are equivalent and express the same api. So what do I miss here?? Why are completely different patterns created for both files? And how can I influence it?

Cheers and thanks for your help,
André

**Comment by jpbelang** [comment]
To get jackson annotations, you need to require them.  Are you using maven or the command line ?

On the command line, -e jackson will add annotations to raml data types. 

Maven example here:
https://github.com/mulesoft-labs/raml-for-jax-rs/tree/master/raml-to-jaxrs/examples/maven-examples

**Comment by jpbelang** [comment]
FYI, the "good" example works because jsonschema is delegated to jsonschema2pojo, which generates json objects (for jackson by default).

**Comment by TheOneAndOnlyAndreKempe** [comment]
Hej JP,

I'm using Maven for that project. I included the generator using the follwoing plugin-section in pom.xml

`<plugin>
                <groupId>org.raml</groupId>
                <artifactId>raml-to-jaxrs-maven-plugin</artifactId>
                <version>2.0.0</version>
                <configuration>
                    <ramlFile>example_json_schema.raml</ramlFile>
                    <resourcePackage>de.tt.api</resourcePackage>
                    <jsonMapper>jackson</jsonMapper>
                    <jsonMapperConfiguration>
                        <includeHashcodeAndEquals>false</includeHashcodeAndEquals>
                    </jsonMapperConfiguration>
                </configuration>
                <executions>
                     <execution>
                        <id>generate-api-sources</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>`

However, neither with jackson-mapper nor jackson2 those json-objects are generated. Or will they only be created when generation is done by jsonschema??

**Comment by jpbelang** [comment]
```xml
<plugin>
                <groupId>org.raml</groupId>
                <artifactId>raml-to-jaxrs-maven-plugin</artifactId>
                <version>2.0.1-SNAPSHOT</version>
                <configuration>
                    <ramlFile>${project.build.resources[0].directory}/types_user_defined.raml</ramlFile>
                    <resourcePackage>example.resources</resourcePackage>
                    <modelPackage>example.model</modelPackage>
                    <resourcePackage>example.types</resourcePackage>
                    <supportPackage>example.support</supportPackage>
                    <generateTypesWith>
                        <value>jackson</value>
                    </generateTypesWith>
                </configuration>
            </plugin>
```

The important part is the **generateTypesWith* part.

**Comment by TheOneAndOnlyAndreKempe** [comment]
Argh, thats exactly the part that i missed! 

I added the respective entry to the pom.xml, switched over to the "bad" example and it worked without any further problems!

Thank you very much for your help and support!!

Cheers,
André
