### ISSUE TITLE
Do we support RAML 0.8?

### ISSUE THREAD

**Issue by kumaranae** [mulesoft-labs/raml-for-jax-rs#268]
Hi Team,

Do we support RAML 0.8?

Do help me by sharing any document which talks about the RAML 0.8 support.

**Comment by sichvoge** [comment]
Did you try to use RAML 0.8? It is supported.

**Comment by kumaranae** [comment]
Am trying to make use of Maven plugin to generate RAML during build time. I could see it creates RAML 1.0. How to make it to generate RAML 0.8 ?

**Comment by jpbelang** [comment]
the to-raml side only generates 1.0

**Comment by JimPartin** [comment]
trying to use ramltojaxrs cli tool on a 0.8 raml file. It will generate resources based on the -r flag (using 2.1.0 and 2.1.1), but will not generate any model files with the -m flag. Keeps crashing with errors.

The older 1.3.x tool seems to have no problem.

error:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NullPointerException
        at com.squareup.javapoet.ClassName.<init>(ClassName.java:52)
        at com.squareup.javapoet.ClassName.<init>(ClassName.java:43)
        at com.squareup.javapoet.ClassName.get(ClassName.java:177)
        at org.raml.jaxrs.generator.ResponseSupport.buildSupportClasses(ResponseSupport.java:53)
        at org.raml.jaxrs.generator.CurrentBuild.generate(CurrentBuild.java:113)
        at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:116)
        at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:72)
        at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:55)
        at org.raml.jaxrs.ramltojaxrs.Main.main(Main.java:75)

**Comment by jstoiko** [comment]
@JimPartin, can you share your RAML or a sample of it?

**Comment by JimPartin** [comment]
sure, tho I also threw the stress test api.raml at it and got a similar result.

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NullPointerException
        at com.squareup.javapoet.ClassName.<init>(ClassName.java:52)
        at com.squareup.javapoet.ClassName.<init>(ClassName.java:43)
        at com.squareup.javapoet.ClassName.get(ClassName.java:195)
        at org.raml.jaxrs.generator.v10.types.V10GTypeJson.defaultJavaTypeName(V10GTypeJson.java:85)
        at org.raml.jaxrs.generator.SchemaTypeFactory.createJsonType(SchemaTypeFactory.java:64)
        at org.raml.jaxrs.generator.v10.types.V10GTypeJson$1.onJsonObject(V10GTypeJson.java:108)
        at org.raml.jaxrs.generator.GObjectType$4.dispatch(GObjectType.java:50)
        at org.raml.jaxrs.generator.v10.types.V10GTypeJson.construct(V10GTypeJson.java:103)
        at org.raml.jaxrs.generator.GeneratorType.construct(GeneratorType.java:85)
        at org.raml.jaxrs.generator.CurrentBuild.constructClasses(CurrentBuild.java:266)
        at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:84)
        at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:75)
        at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:56)
        at org.raml.jaxrs.ramltojaxrs.Main.main(Main.java:75)

**Comment by jstoiko** [comment]
can you provide the cli command?

**Comment by JimPartin** [comment]
Sure, i've tried various variations, last run is:

java -jar raml-to-jaxrs-cli-2.1.1-SNAPSHOT-jar-with-dependencies.jar -d ./tmp ./api.raml

**Comment by JimPartin** [comment]
for the original 0.8 file...:
#%RAML 0.8
title: thing1-oe-data-services-stuffs
baseUri: http://foo.bar.baz/thing1/oe/services/data/v1/stuffs

schemas:
- w00t: !include schemas/w00t-schema.json
- errorSchema: !include schemas/error-schema.json

/{var1}/op2/{var2}/op3/{var3}/op4/{var4}/op5/{op5}:
  get:
    description: la le li lu lo
    responses:
      200:
        body:
          application/json:
            schema: w00t
      404:
        body:
           application/json:
              schema: errorSchema

w00t-schema.json:
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "w00t",
  "description": "la le lu li lo",
  "type": "object",
  "properties": {
    "someId": {
        "type": "integer"
    },"someInt": {
        "type": "integer"
    },"aString": {
        "type": "string"
    },"anotherString": {
        "type": "string"
    },
      "blah": {
          "type": "string"
      },"anotherInt": {
          "type": "integer"
      }
  },
  "required": ["someId", "someInt","aString", "anotherString","blah"]
}

error-schema.json:
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Error",
  "description": "A Error Detail",
  "type": "object",
  "properties": {
    "code": {
        "type": "string"
    },
      "message": {
          "type": "string"
      }
  },
  "required": ["code", "message"]
}

Command:
java -jar raml-to-jaxrs-cli-2.1.1-SNAPSHOT-jar-with-dependencies.jar -d ./tmp -m org.foo.bar.models ./myRaml.raml

**Comment by JimPartin** [comment]
btw, the code line for javapoet from the 2.1.1 build in the trace is com.squareup.javapoet.ClassName.get(ClassName.java:177) instead of 195.

I updated javapoet to 1.8 to attempt to resolve, yield line 195.

**Comment by jstoiko** [comment]
Not sure what the issue is but I tested with 2.1.0 following `raml-to-jaxrs/README` and was able to generate the code.
```
$ cd raml-to-jaxrs/raml-to-jaxrs-cli/
$ mvn clean install
$ java -jar ./target/raml-to-jaxrs-cli-2.1.0-jar-with-dependencies.jar  -d /tmp -r foo.bar ./myraml.raml
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
$ ls /tmp/foo/bar/
ResponseDelegate.java                Var1Op2Var2Op3Var3Op4Var4Op5Op5.java
$ cat /tmp/foo/bar/Var1Op2Var2Op3Var3Op4Var4Op5Op5.java 
package foo.bar;

import java.lang.Object;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Response;

@Path("/{var1}/op2/{var2}/op3/{var3}/op4/{var4}/op5/{op5}")
public interface Var1Op2Var2Op3Var3Op4Var4Op5Op5 {
  @GET
  @Produces("application/json")
  GetOp2Op3Op4Op5Response getOp2Op3Op4Op5();

  class GetOp2Op3Op4Op5Response extends ResponseDelegate {
    private GetOp2Op3Op4Op5Response(Response response, Object entity) {
      super(response, entity);
    }

    private GetOp2Op3Op4Op5Response(Response response) {
      super(response);
    }

    public static GetOp2Op3Op4Op5Response respond200WithApplicationJson(W00t entity) {
      Response.ResponseBuilder responseBuilder = Response.status(200).header("Content-Type", "application/json");
      responseBuilder.entity(entity);
      return new GetOp2Op3Op4Op5Response(responseBuilder.build(), entity);
    }

    public static GetOp2Op3Op4Op5Response respond404WithApplicationJson(ErrorSchema entity) {
      Response.ResponseBuilder responseBuilder = Response.status(404).header("Content-Type", "application/json");
      responseBuilder.entity(entity);
      return new GetOp2Op3Op4Op5Response(responseBuilder.build(), entity);
    }
  }
}
```

**Comment by JimPartin** [comment]
Thank you for taking the time to look into this. The -r flag seems to work fine most of the time, it's the -m flag to generate the model files that I am most concerned with. It repeatedly fails with the errors given. When run with no flags, it appears that the tool tries to perform all 3 operations, failing at the model generation (also fails with the -s support generation). When only using the -r flag, the tool completes normally, generating only those files.

**Comment by jstoiko** [comment]
I see. that's odd. have you tried using the maven plugin?

@jpbelang can you take a look?

**Comment by JimPartin** [comment]
Should I create a new Issue for this problem?

**Comment by jstoiko** [comment]
I may have closed this by mistake. Sorry. Anyway, yes please go ahead and create a separate issue.
