### ISSUE TITLE
2.0.1 snapshot in snaphots repository

### ISSUE THREAD

**Issue by kumaranae** [mulesoft-labs/raml-for-jax-rs#270]
Hi Team,

Can you please deploy the 2.0.1-snapshots into the below maven repository,

https://repository-master.mulesoft.org/snapshots/ - snaphots repository

Please include the below fixes into the snapshot, since we need those for our release at the earliest.

ClassCastException with recent changes
NPE when @Provider used in class
RAML validation fails with ":" in description
RuntimeException with Unknown type

Regards,
Kumaran.A.E

**Comment by jstoiko** [comment]
@kumaranae: 2.1.0-SNAPSHOT is now on https://repository-master.mulesoft.org/snapshots/ and 2.1.0 has been released so it's now also on https://repository-master.mulesoft.org/releases/

Please note that the groupId has changed from `org.raml` to `org.raml.jaxrs` so you'll need to update your POM file(s) accordingly.

The good news is that snapshots are now setup to automatically build & deploy to https://repository-master.mulesoft.org/snapshots/ so anyone will be able to get the latest build without having to build manually locally. Also, note that releases are organized in separate branches following the naming convention `release/<version>`.
