### ISSUE TITLE
Customizing the class name or method name

### ISSUE THREAD

**Issue by vijayrcse** [mulesoft-labs/raml-for-jax-rs#273]
Hi 

We used below extension to customize a method name in RAML 0.8 code gen plugin

<extensions> <extension>org.raml.jaxrs.codegen.core.ext.ResourceDisplayNameBasedMethodNameBuilder</extension>
</extensions>

But we could not use this for the RAML 1.0 code gen plugin ( RAML to JAX RS )

Could you please advise if this support can be added back ?

**Comment by jpbelang** [comment]
Yes you can!
There is a plugin (a bit experimental) in the code that allows for all sorts of stuff.

That said, I'd like to build a rename plugin for y'all.  Liek I said, it's a bit experimental, but if you want to look at it, some examples here:

https://github.com/mulesoft-labs/raml-for-jax-rs/tree/master/raml-to-jaxrs/examples/maven-examples/features/feature-plugins/src/main/java/org/raml/jaxrs/features

**Comment by jpbelang** [comment]
It uses RAML annotations, BTW.

**Comment by vijayrcse** [comment]
yep thanks a lot. I was also looking into this features example. will give a try
