### ISSUE TITLE
When will 2.0.1 will be released ?

### ISSUE THREAD

**Issue by vijayrcse** [mulesoft-labs/raml-for-jax-rs#274]
Hi 
Could you advise when 2.0.1 will be released. We are expecting some fixes from this version to be used

Thanks & Regards
-Vijay

**Comment by jstoiko** [comment]
it should be out by end of this week. thanks for your patience!

**Comment by vijayrcse** [comment]
Thanks jstoiko for the update

**Comment by vijayrcse** [comment]
just curious, is the release is out for 2.0.1 ?
Can we have at least an RC ?( we don;t want to rely on snapshot )

**Comment by jstoiko** [comment]
sorry this is taking longer than expected. we're still working out a few issues. one of them is related to deployment, hence why we don't have SNAPSHOTs published on the MuleSoft Nexus repository. I will keep you updated. Thanks for you patience.

**Comment by vijayrcse** [comment]
Thanks for the update Jon. Please let us know once a release is pushed

**Comment by vijayrcse** [comment]
Hi Jon,
The main reason we are looking for 2.0.1 is for the below fix 
https://github.com/mulesoft-labs/raml-for-jax-rs/issues/231

this is preventing us to use the maven plugin in pom.

Any eta for the release for 2.0.1 that you have in mind ?

Thanks 
-Vijay

**Comment by jstoiko** [comment]
Hey @vijayrcse, the latest release is now 2.1.0. It's only on MuleSoft's nexus/maven repo at the moment but we are working on syncing it w/ Maven Central. Closing this issue.

**Comment by vijayrcse** [comment]
hey thanks a lot , we will test this. Thanks for the help

**Comment by jstoiko** [comment]
@vijayrcse: 2.1.0 is on Maven Central now: http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.raml.jaxrs%22
