### ISSUE TITLE
How to use raml-2-jaxrs maven plugin to map type in raml file to Model interface in Java

### ISSUE THREAD

**Issue by YangYangX** [mulesoft-labs/raml-for-jax-rs#277]
Hi,

I am trying to using raml-to-jaxrs-maven-plugin[2.0.0] to convert raml file into java classes, everything thing works well until it comes to "POST" request, I got a error: 
com.fasterxml.jackson.databind.JsonMappingException: abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information

And I found in one of the Model class, Product.java, the interface is missing @JsonDeserialize annotation.

Don't know if I did something wrong in the raml file or the plugin is not working properly in this case?
Can someone please help me out here?

Thanks a lot!!

**Comment by jpbelang** [comment]
Check the examples (the raml types one, sorry working from memory).  There is a generateTypesFor tag.  put jackson in there.

Check issue #267 

PS:  I really should fail on some of these situations.  :-/

**Comment by YangYangX** [comment]
Thanks a lot!! It works now!!
