### ISSUE TITLE
Multiple ramlFiles

### ISSUE THREAD

**Issue by giacgbj** [mulesoft-labs/raml-for-jax-rs#279]
According to [RamlJaxrsCodegenMojo.java](https://github.com/mulesoft-labs/raml-for-jax-rs/blob/821cc8864a690864e226a3465e49e27163fe8954/raml-to-jaxrs/raml-to-jaxrs-maven-plugin/src/main/java/org/raml/jaxrs/codegen/maven/RamlJaxrsCodegenMojo.java):

```
 /**
   * An array of locations of the RAML file(s).
   */
  @Parameter(property = "ramlFile", required = true)
  private File ramlFile;
```

However, it doesn't handle multiple locations.

**Comment by jpbelang** [comment]
Please see #315
