### ISSUE TITLE
Raml response code is not taking headers from raml file

### ISSUE THREAD

**Issue by ankitabankbazaar** [mulesoft-labs/raml-for-jax-rs#281]
/tiny:
   /{id}:
       uriParameters:
           id:
               type: string
       post:
           responses:
               302:
               headers:
                   Location:
                       description: Redirected Location
                    
When I ran Code Generator...
it didnt do anything to the header

The generated code was 

public static PostTinyByIdResponse respond302() {
Response.ResponseBuilder responseBuilder = Response.status(302);
return new PostTinyByIdResponse(responseBuilder.build());
}

It is not taking redirect location url in parameter. It is an issue if i want to set different redirect url for each request, then i can not use this.

**Comment by jpbelang** [comment]
Certainly doable.  I actually like this and hadn't thought of it. I'll try to get this in this week.  We are trying to release 2.1.  I'll do my best :-)

That said, couldn't you, in the implementation, set the location ?

**Comment by ankitabankbazaar** [comment]
@jpbelang I can't set location in implementation because getResponse is private to the class and there is no other option i am getting to set the location for response.

**Comment by jpbelang** [comment]
@ankitabankbazaar I've got something to try.  I don't like the way the headers class is built. Is this long the lines of what you would like  ?
