### ISSUE TITLE
v2.1.0 - Inline generation doesn't seems to be recursive

### ISSUE THREAD

**Issue by tarteens** [mulesoft-labs/raml-for-jax-rs#285]
Here the snippet for the raml, and the generated class
[inline.zip](https://github.com/mulesoft-labs/raml-for-jax-rs/files/1121233/inline.zip)

Using 2.1.0-SNAPSHOT

Hi, 

I try to design some raml, without explicitly declaring each type of my properties.
Basically I have a root type "MyInlineObject" with a couple properties which 2 of them are declared inline. 
The problem is that the auto-generated class are not correctly generated. 

After having look at the code, it seems the problem lie on the **SimpleInheritanceExtension** class. 
When processing an inline declaration, it inner name is an integer (representing a counter) **internalTypeName** 

The problem lie between the Registry being global to the all raml generation, and this **internalTypeCounter** being reseted to 0. 

You can reproduce this issue with the attached file.

**Comment by jpbelang** [comment]
Looking into it.  Inlines are a pain that are not currently helped by the parser.
