### ISSUE TITLE
MediaType application/octet-stream support

### ISSUE THREAD

**Issue by giacgbj** [mulesoft-labs/raml-for-jax-rs#288]
The following RAML produces a class which uses the type ApplicationOctetStream without creating the class ApplicationOctetStream itself:
```
  /foo:
    get:
     responses:
       200:
         body:
           application/octet-stream:
```
Is there anything wrong in the RAML or it isn't supported yet?

**Comment by jpbelang** [comment]
I don't think it's handled.  This is your whole raml ?

Having something in the response delegate to write the response could be an idea, correct (since there is no RAML type...) ?

**Comment by giacgbj** [comment]
If you mean that there's no type at the end, that's the full RAML because I don't need a type since it's an octet-stream.

Googling around it seems that the suggested solution is to use StreamingOuput. Somethign like https://stackoverflow.com/questions/12012724/example-of-using-streamingoutput-as-response-entity-in-jersey using octet-stream as media type and passing the InputStream to write.

**Comment by jpbelang** [comment]
Yes I mean no type and yes I agree it's not needed.  I'll do the SO solution tonight.  Or at lunchtime.

**Comment by jpbelang** [comment]
Check this please ?

**Comment by giacgbj** [comment]
It works. Thanks for your prompt feedbacks!
Waiting for the release ;-)
