### ISSUE TITLE
Headers support

### ISSUE THREAD

**Issue by giacgbj** [mulesoft-labs/raml-for-jax-rs#289]
It seems that headers are ignored. Are you going to support them?

```
/foo:
  post:
    headers:
      X-Custom-Header:
        type: string
[...]
```

**Comment by jpbelang** [comment]
Now they do :-)

Could you check (in release/2.1.0)

**Comment by giacgbj** [comment]
I just tested it and it works.
When are you going to release a new version?

**Comment by jpbelang** [comment]
Good.  August ?

**Comment by giacgbj** [comment]
Looking forward to the release (or I'll have to release it by myself on our repository :anguished:).

**Comment by YangYangX** [comment]
Hi,

Sorry for commenting in a closed issue :P, but has header support been released yet? We are using the raml-2-jaxrs-maven plugin.

**Comment by jpbelang** [comment]
Not yet.  We are trying to sync up with another project to use common code.  It should be soon though.
