### ISSUE TITLE
MessageBodyWriter can't be found, because of ResponseDelegate

### ISSUE THREAD

**Issue by ma-ver-ick** [mulesoft-labs/raml-for-jax-rs#290]
Hi!

Using the ResponseDelegete seems to have problems with Payara 4.1.2.172 (jersey 2.25.1). Using the ResponseDelegate the jersey not able to find it's message body writer

> [#|2017-07-21T08:33:33.658+0000|SEVERE|Payara 4.1|org.glassfish.jersey.message.internal.WriterInterceptorExecutor|_ThreadID=25;_ThreadName=http-thread-pool::http-listener-1(2);_TimeMillis=1500626013658;_LevelValue=1000;
>
>    MessageBodyWriter not found for media type=application/json, type=class java.util.ArrayList, genericType=class java.util.ArrayList.|#]

However, when I use a non-generated rest endpoint without the ResponseDelegate in the same class works flawlessly.
I'm not 100% sure what causes this, maybe jersey uses internal methods to determine the type of the entity... No clue yet.

**Comment by ma-ver-ick** [comment]
After stepping through code, it seems that the following line is killing the normal functionality


```java
// from: org.glassfish.jersey.server.model.ResourceMethodInvoker

// around 378
                if (canUseInvocableResponseType
                        && response.hasEntity()
                        && !(response.getEntityType() instanceof ParameterizedType)) {
                    response.setEntityType(invocableResponseType);
                }
```

This enriches the response with the reflection details of the rest endpoint. So 

```
public List<TestPersonDAO> getPersons2() 

```

is serializable automagically, but 

```
public GetPersonsResponse /* raml generated response wrapper */ getPersons() 

```

is not, because the container can't automagically determine the correct type.
It would be good to have an option to actually generate the correct return types, instead of wrappers. I don't see a safe&nice way to re-inject the correct type information back into the response (without hacking). Any suggestions?

**Comment by jpbelang** [comment]
I'll look into it.  Just so I understand, if the return type is a parameterized type, it has trouble figuring out the paramterized type.  Correct ?

This said, it would be possible to change the return type through a plugin for raml-to-jaxrs.  I'll try to give you an example.

**Comment by ma-ver-ick** [comment]
Thanks!
If the return type is a parameterized type (List<XXX>) it works flawlessly as expected. If the return type is the ResponseDelegate type, it can't find the MessageBodyWriter.

That example would be cool, I have a little trouble with that.

**Comment by jpbelang** [comment]
I'll try tonight or tomorrow.  Most likely tomorrow.

(I sound like a hairdresser:  I have you down for a Thursday plugin example).

**Comment by jpbelang** [comment]
I didn't do the example yet, but I pushed a fix that expands something I did for XML a while back.  It uses GenericEntity for arrays.  Could you try this please ?

on release/2.1.1
