### ISSUE TITLE
Mirror Maven repos to Central or JCenter?

### ISSUE THREAD

**Issue by ascheman** [mulesoft-labs/raml-for-jax-rs#292]
Would you please consider uploading your Maven artifacts or mirroring your repositories to Maven Central or Bintray? It is hard to convince a customer to mirror multiple _special_ repositories in his enterprise Maven cache. Otherwise we are not able to use the latest versions of the artifacts.

**Comment by jstoiko** [comment]
hi @ascheman, we're on it. We've been experiencing difficulties getting it setup in part due to the refactoring and a change of the groupId. It shouldn't take much longer. I'll update this issue once the artifacts have been deployed to Maven Central.

**Comment by jstoiko** [comment]
Raml for JAX-RS is now on Maven Central: https://oss.sonatype.org/#nexus-search;gav~org.raml.jaxrs~~~~

**Comment by jstoiko** [comment]
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.raml.jaxrs%22

**Comment by ascheman** [comment]
Thx!
