### ISSUE TITLE
Generating Wrapper classes(java.lang.Long, java.math.BigDecimal) from the Raml1.0 schemas

### ISSUE THREAD

**Issue by Prudhvee** [mulesoft-labs/raml-for-jax-rs#298]
Hi,

Was able to generate the Wrapper classes from RAML-to-jaxrs in RAML 0.8 using raml-jaxrs-maven-plugin with the following JSON syntax.
**"Interest": {“type":"object", "javaType":"java.math.BigDecimal” }**

Is there a way we can generate the similar Wrapper classes (ex. "java.lang.Long" for "long" in RAML1.0 datatype schema) using the raml-to-jaxrs-maven-plugin?

**Comment by jpbelang** [comment]
In 1.0, on the release/2.2.0 you can annotate the types.
see #329 to setup a plugin.  There is also the core.box plugin.
