### ISSUE TITLE
@ramlGenerator: does not parse the property of a class

### ISSUE THREAD

**Issue by hshah8831** [mulesoft-labs/raml-for-jax-rs#300]
I am using @RamlGenerator(SimpleJacksonTypes.class) to get the RAML type in raml 1.0 It does recognize the java class but cannot get the properties.

However, my class has @JsonProperty annotation. Please let me know in case you need more information.

**Comment by jpbelang** [comment]
Can you show me an example class ?

**Comment by hshah8831** [comment]
This is what I have
```java
@RamlGenerator(SimpleJacksonTypes.class)
public class UserAccount implements Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    @JsonProperty
    private User userInfo;
    @JsonProperty
    private List<Account> accounts;
    
    public User getUserInfo() {
        return userInfo;
    }
    public void setUserInfo(User userInfo) {
        this.userInfo = userInfo;
    }
    public List<Account> getAccounts() {
        return accounts;
    }
    public void setAccounts(List<Account> accounts) {
        this.accounts = accounts;
    }
  
}
```
And couple of other like this
This generates types as follows

types:
    Account:
        description: This class provides info about an account
    AccountAuthPolicy:
        description: 
    UserAccounts:
        description: 
    User:
        description:

**Comment by hshah8831** [comment]
Just to add to the question and give a little context.

As you can guess, I am trying to generate a Raml from jax-rs. I am able to create a raml file but there are certains issues.

It does not include definition of "type" for List, HashSet etc. 
I am using the @ramlgenerator to generate the raml types, but it does not give me properties. It would be great if you can give an example of customization of TypeHandler, and some more details of when to use which out of SimpleJacksonTypes and BeanLikeTypes, and when would it justify customization.

Thanks

**Comment by jpbelang** [comment]
Ok, I'll try to get in to look at this tonight.

**Comment by jpbelang** [comment]
Sorry for the delay.  Right now, I only look for annotations on methods.  I'm trying to fix it now.  Might not be dne tonight.

**Comment by jpbelang** [comment]
I've just made a test example with your setup and is seems to generate properly.  I've got an example in the pipes for a type handler. They are fairly simple: look at org.raml.jaxrs.handlers.SimpleJacksonTypes and you could change the TypeScanner internal class.
