### ISSUE TITLE
Support of @JsonSubTypes annotation in generated types

### ISSUE THREAD

**Issue by vijayrcse** [mulesoft-labs/raml-for-jax-rs#301]
Hi ,

My autogenerated type class looks like this

class BaseProduct implements Product {
    protected ProductDescriptor descriptor;
}

Since here ProductDescriptor  is an interface , ObjectMapper's readValue(InputStream in, Class<T> valueType) method throws below exception

com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of ProductDescriptor  r, problem: abstract types either need to be mapped to concrete types, have custom deserializer, or be instantiated with additional type information

To solve I require to annotate my interface generated as follows

`@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "type")
@JsonSubTypes({
    @Type(value = ProductDescriptorImpl.class, name = "mvdimpl") })
interface ProductDescriptor
{
   ...
}`

Could you please advise how I can make this custom annotation generated as part of types ?
is it supported as part of feature plugin ?

**Comment by jpbelang** [comment]
You don't seem to be generating automatic jackson2 annotations.

On the command line, add **-g jackson**

In maven, look at the examples.  Add
```xml
                    <generateTypesWith>
                        <value>jackson</value>
                    </generateTypesWith>
```

**Comment by vijayrcse** [comment]
Got it it worked. thanks a lot
