### ISSUE TITLE
Complex types JSR 303 validation 

### ISSUE THREAD

**Issue by giacgbj** [mulesoft-labs/raml-for-jax-rs#302]
What happened to the feature added by the pull request https://github.com/mulesoft-labs/raml-for-jax-rs/pull/161 ?

**Comment by jpbelang** [comment]
there is an option for jsr303 annnotations on raml types.  

The maven version: 
https://github.com/mulesoft-labs/raml-for-jax-rs/blob/821cc8864a690864e226a3465e49e27163fe8954/raml-to-jaxrs/examples/maven-examples/README.md

-g jsr303 on the command line

**Comment by giacgbj** [comment]
I'm using that option, but the `@Valid` annotation is not produced on complex methods.

**Comment by jpbelang** [comment]
Like this ?

**Comment by giacgbj** [comment]
I find it difficult to test it because

```
<groupId>org.raml.jaxrs</groupId>
<artifactId>raml-to-jaxrs-maven-plugin</artifactId>
<version>2.1.1-20170924.235018-16</version>
```

has a parent pom which refers to 

https://repository-master.mulesoft.org/nexus/content/repositories/snapshots/org/raml/jaxrs/raml-to-jaxrs/2.1.1-SNAPSHOT/maven-metadata.xml

and points to a non-existing artifact 

2.1.1-20170924.235014-16

while the artifact has the version

2.1.1-20170924.235013-16

As you can see, it seems the seconds passed between the release of the snapshots.

**Comment by giacgbj** [comment]
maven-metadata.xml has been corrected.

I tested the code but it doesn't work as I expected.

Given the following (simplified) RAML:

```
Foo: 
    type: string
    minLength: 5

Bar:
    properties:
        foo: Foo

/jhack:
    put:
        body:
            application/json: Bar
```
       
the following code should be produced:

```
@PUT
@Consumes("application/json")
PutJhackResponse putJhack(@Valid Bar entity);    
```

**Comment by jpbelang** [comment]
Ok, no problem.  I thought you had meant the @Valid annotation on child object of a composite object.

I know what you mean.

**Comment by giacgbj** [comment]
It works properly for my actual needs. 
When are you going to release a new version?
