### ISSUE TITLE
Support for jackson 1.x annotations( codehaus )

### ISSUE THREAD

**Issue by vijayrcse** [mulesoft-labs/raml-for-jax-rs#303]
We have some projects using Jackson 1.9 where we use the below provider

org.codehaus.jackson.jaxrs.JacksonJsonProvider

Since the model object are generated as interfaces & classes we get below exception during deserialization

org.codehaus.jackson.map.JsonMappingException: Can not construct instance of com.org.Employee, problem: abstract types can only be instantiated with additional type information

is it possible that model classes generated support Jackson 1

note : we are using datatypes in RAML
Please advise

**Comment by mikkoi** [comment]
Also I fail with Jackson1 generation.
Can you share your config? Maven?

**Comment by jpbelang** [comment]
See #332
