### ISSUE TITLE
Path parameters nowhere to be found

### ISSUE THREAD

**Issue by DavideRossi** [mulesoft-labs/raml-for-jax-rs#313]
A path like this:
/polls/{pollId}
creates a method in the main interface like that:
```
@GET
@Path("/polls/{pollId}")
@Produces("application/json")
GetDoodlePollsResponse getDoodlePolls();
```
How am I supposed to retrieve the pollId path parameter from within the implementation of getDoodlePolls?

FYI: if I use SAP's code generator (service-sdk-generator-maven-plugin) the method looks like that (which, to me, seems the more reasonable thing):
```
@javax.ws.rs.Path("/polls/{pollId}")
@javax.ws.rs.GET
@javax.ws.rs.Produces({"application/json"})
Response getDoodlePolls(@javax.ws.rs.PathParam("pollId") final java.lang.String pollId);
```
BTW: I'm using the maven plugin (v 2.1.0)

**Comment by jpbelang** [comment]
The path doesn't enter into it.  you need:
uriParameters:
      pollId: string

I don't parse (or check) the URL.

**Comment by DavideRossi** [comment]
Thanks Jean-Philippe.
Then maybe we can change that to an enhancement request?
This would also solve #314 ...

**Comment by jpbelang** [comment]
It really can't be an enhancement request:  if you don't have the queryParameters and your url is 

/foo/{bar}

The raml spec says that you are publishing, literally, that URL.  Not having the parameters essentially break what you are trying to say with the curly braces.

**Comment by DavideRossi** [comment]
To me, it seems more convoluted than that. This is from the specs:

> All URI parameters in the relative URI do not need to be explicitly specified in the uriParameters node, but those that are not specified MUST be treated as a URI parameter of type string and required.

**Comment by jpbelang** [comment]
Aw.  Crap.  I hadn't seen that.  And the parser doesn't seem to support it. Double crap. :-)

"Thanks".  I'll take your request under advisement (I'll see how the parser team feels about it).

In the meantime, is it a major hassle to put the parameters in ?  This works. :-)

**Comment by jpbelang** [comment]
https://github.com/raml-org/raml-java-parser/issues/201

**Comment by jpbelang** [comment]
I've worked around this in #314
