### ISSUE TITLE
Code generation for multiple RAML files - using maven plugin

### ISSUE THREAD

**Issue by vijayrcse** [mulesoft-labs/raml-for-jax-rs#315]
Hi

I have multiple RAML files in by maven project. How to configure the maven plugin such that code generation happens for all the RAML

Currently I have something like below. How to change below so I can provide multiple RAML files references

```
<plugin> 
<groupId>org.raml.jaxrs</groupId> 
<artifactId>raml-to-jaxrs-maven-plugin</artifactId> 
<version>${project.version}</version> 
<configuration> 
  **<ramlFile>${project.build.resources[0].directory}/types_user_defined.raml</ramlFile>** 
  <resourcePackage>example.resources</resourcePackage> 
  <modelPackage>example.model</modelPackage> 
  <resourcePackage>example.types</resourcePackage> 
  <supportPackage>example.support</supportPackage> 
  <generateTypesWith> 
    <value>jackson</value> 
  </generateTypesWith> 
</configuration> 
</plugin>
```

**Comment by jpbelang** [comment]
I'm trying to configure the mojo for multiple executions, but for some reason, configuration-per-execution isn't working.  I can't figure out why this is failing.  I have some questions pending.

**Comment by jpbelang** [comment]
I've added an example of multiple files in one of the  examples(I've actually changed the plugin)

raml-to-jaxrs/examples/maven-examples/raml-defined-example/pom.xml

If the ramlFile is a directory, the the includes and excludes kick in.  We do a recursive search for files.

**Comment by vijayrcse** [comment]
thanks for looking into this. I shall take a look at the example
