### ISSUE TITLE
Configuration Option to skip generating Resources and Support optoins

### ISSUE THREAD

**Issue by kingargyle** [mulesoft-labs/raml-for-jax-rs#323]
I'm I'm interested in really is the ability to generate the POJO data types with Jackson Annotations.  I know there is the ramltopojo tools project under development, but  didn't see where that had built in support for Jackson.   somthing like skipResources = true, and skipSupport = true.

**Comment by jpbelang** [comment]
Not sure what you mean:  ramltopojo will support jackson2 annotations (this will appear on the weekend).  That will only build the pojos.

Will that do what you want ?

**Comment by kingargyle** [comment]
Yep, that will do what I need.  Closing this request.
