### ISSUE TITLE
RAML to POJO - description and displayName

### ISSUE THREAD

**Issue by giacgbj** [mulesoft-labs/raml-for-jax-rs#324]
Are you planning to support description and displayName fields?

**Comment by jpbelang** [comment]
The description would be pulled from the javadocs.  Where would you want the displayname to go ?

**Comment by giacgbj** [comment]
According to the documentation:

- displayName: An alternate, human-friendly name for the resource. If the displayName node is not defined for a resource, documentation tools SHOULD refer to the resource by its key, which acts as the resource name.
- description: A substantial, human-friendly description of a resource. Its value is a string and MAY be formatted using markdown.

It's not extremely clear how to use them :-)

We can probably use only description for the Javadoc.

**Comment by jpbelang** [comment]
On release/2.2.0, I've added the description as javadoc, pretty much straight up.
