### ISSUE TITLE
Returning of Lists with non primitives not possible

### ISSUE THREAD

**Issue by frl7082** [mulesoft-labs/raml-for-jax-rs#325]
The generation of Lists with non primitive types is not possible.
See this Raml:
```raml
#%RAML 1.0
---
title: Test api
version: v1
protocols: [ HTTPS ]

baseUri: https://foo.bar/
mediaType: application/json

types:
  A:         !include model/A.schema.json
  AList1:    !include model/AList.schema.json
  AList2:                 
    type: array
    items:
      type: A

/foo:
  get:
    responses:
      200:
        body:
          type: AList1

/bar:
  get:
    responses:
      200:
        body:
          type: AList2
```
Where A.schema.json is just a simple object. An AList.schema.json is only an array with A as item.

The generation fails with the message:
```
Exception in thread "main" org.raml.jaxrs.generator.GenerationException: [Invalid facets for type A: array type cannot be of an external type. -- C:/tmp/example/ [line=14, col=5]]
        at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:59)
        at org.raml.jaxrs.generator.RamlScanner.handle(RamlScanner.java:51)
        at org.raml.jaxrs.ramltojaxrs.Main.main(Main.java:87)
```

This is because of the definition of AList2

If this is removed the generation works, however the result class of AList is just exactly like the generated class of A, and not a List.

The result of the foo interface contains:
```java
/* ... */
public static GetFooResponse respond200WithApplicationJson(AList entity) {
      Response.ResponseBuilder responseBuilder = Response.status(200).header("Content-Type", "application/json");
      responseBuilder.entity(entity);
      return new GetFooResponse(responseBuilder.build(), entity);
    }
/* ... */
```

But it should be:

```
/* ... */
public static GetFooResponse respond200WithApplicationJson(List<A> entity) {
      Response.ResponseBuilder responseBuilder = Response.status(200).header("Content-Type", "application/json");
      responseBuilder.entity(entity);
      return new GetFooResponse(responseBuilder.build(), entity);
    }
/* ... */
```

So there are two issues here:
1. The generation from schemas beeing only an array type is not correct.
2. The inline type definition of an array with an external type as item class is not working.

See the complete example [here](https://github.com/mulesoft-labs/raml-for-jax-rs/files/1634326/example.zip)

**Comment by jpbelang** [comment]
Is this with the latest release ?

**Comment by frl7082** [comment]
Yes, with the current 2.1.1 release.

For 2. it seems it was made illegal on purpose. However I don't quite get why. [LINK](https://github.com/raml-org/raml-java-parser/commit/0cf66bd2787afefd2f5b417c244ff0d160b0fbf8#diff-0073956544fd88bd877e789dc6a437c4)

**Comment by jpbelang** [comment]
Well, the problem you have is that you are using jsonschema types and the parser won't ever parse a list of jsonschema objects.  I think it's in the RAML spec.  This is out of my control.

I'm supposing the AList schema contains a list of A ?  Does this not work ?

**Comment by frl7082** [comment]
Yeah, you're right. I've just reread the spec.

Yes, AList is something  like:

{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "array",
	"items": {
		"$ref": "A"
	}
}

But the created AList.java is just exactly like the A.java, however everywhere the AList is used, I would expect List<A> to be generated. 
With the 1.3.4 version this worked as expected.

**Comment by jpbelang** [comment]
I'll look at what you get.  I'll come back to you.  

My opinion though, is that you should try to migrate to RAML types (I understand that you might not be able to)

**Comment by frl7082** [comment]
Any progress on this one. Unfortunatly migrating to RAML types is not possible atm.

**Comment by jpbelang** [comment]
Yes, I've been reading on the subject and trying stuff.  
jsonschematopojo does not generate collection classes (https://github.com/joelittlejohn/jsonschema2pojo/issues/202).  The normal way of doing this seems to be (in raml08) to have a schema object that contains a collection property and to use this.

Now, in 1.0, you could write a plugin where you replace the generated parameters (A a, for example) to A container (List<A> listOfA).  I think this would work as your jsonschema actually would correspond to your AList schema.

**Comment by frl7082** [comment]
Fun thing is, with version 1.3.x (and raml 0.8) the List<A> was generated correctly. Wasn't this also delegating to jsonschema2pojo?

**Comment by jpbelang** [comment]
Yes, but I didn't manage to get it to work in the old code either.   Do you have a 0.8 example ?  I might have translated it wrong.

**Comment by frl7082** [comment]
Here is a working [example](https://github.com/mulesoft-labs/raml-for-jax-rs/files/1775127/example.zip)

**Comment by jpbelang** [comment]
Thanks, I'll run it this PM.

**Comment by jpbelang** [comment]
I've figured out what is going on.  I use jsonschematopojo in a different way (pretty different).  
My code is generated with JavaPoet in general.  External classes are delegated to jaxb and js2pojo, which use CodeModel.  This is not generally problematic, in general, but you've hit on a non-trivial problem, namely that I could have to parse the codemodel structures to figure out what is going on.

We are currently trying to release and it would be a really bad idea to change something like this.  

3.0.1 ?

**Comment by frl7082** [comment]
Hmm, unfortunately I cannot continue on my project until this is fixed :(
Any idea for a temporary workaround? You've mentioned a plugin?

**Comment by jpbelang** [comment]
yes, of course.  I'll build a method plugin where you can force the type of the input value to list of something.  You can say what the something is.  

It should be called something like "workaround.listOf".  I'll try to do this tonight.

**Comment by jpbelang** [comment]
Please check the type torture test and add the plugin. You can put any type in the 
annotation.

```yaml
uses:
  SongsLib: libraries/songs-library.raml
  ApiLib: libraries/api-library.raml
  ramltojaxrs: ramltojaxrs.raml

/jsonThing:
    /bar:
        get:
          responses:
            200:
              (ramltojaxrs.responses):
                plugins:
                  - name: workaround.entityListType
                    arguments: [java.lang.String]
              body:
                application/json:
                  type: TypeToChange
        put:
          (ramltojaxrs.methods):
            plugins:
              - name: workaround.entityListType
                arguments: [java.lang.String]
          body:
            application/json:
              type: TypeToChange

**Comment by frl7082** [comment]
Thank you really much for your help! I think the fix is only available in 3.0 ? Any plans when 3.0 is released?

**Comment by jpbelang** [comment]
Any minute now.  The code is complete.

**Comment by frl7082** [comment]
So? Still no release? :(

**Comment by frl7082** [comment]
Please note, that this is not completely finished. Only a workaround is provided
