### ISSUE TITLE
Add possibility to generate uriParameters as longs

### ISSUE THREAD

**Issue by frl7082** [mulesoft-labs/raml-for-jax-rs#328]
When having an uriParameter with type "integer" it is generated as "int". Please add the possibility to generate it as "long"

**Comment by jpbelang** [comment]
Yup.  it should be possible with the new object generator.  Will post an answer on the weekend.

**Comment by jpbelang** [comment]
Sorry for the delay:  on release/2.2.0.

This can be done with the changeType plugin.  Without the unbox parameter, you keep the java.lang.Long:
```yaml
#%RAML 1.0
title: Hello World API
version: v1
baseUri: https://api.github.com
mediaType: application/json
uses:
  ramltopojo: ramltopojo.raml
/search:
    description: The search resource
    uriParameters:
        id:
            type: integer
            (ramltopojo.types):
              plugins:
                - name: core.changeType
                  arguments: [ java.lang.Long, unbox ]
    get:
        body:
            text/plain:
                type: string
        responses:
            200:
                body:
                    application/json:
                        type: string
```
The contents of ramltopojo.raml is
```yaml
annotationTypes:
    types:
        allowedTargets: [TypeDeclaration,API]
        properties:
            className?:
                type: string
            implementationClassName?:
                type: string
            usePrimitiveType?:
                type: boolean
            abstract?:
                type: boolean
            plugins?: any[]

**Comment by frl7082** [comment]
Thank you! To be honest, I've expected something like the "useLongIntegers" option in jsonschema2pojo, but this will also work.

**Comment by jpbelang** [comment]
Just FYI:  
There is a format facet to integer and number in raml.  You can also use this.  Maybe that's better.  I implemented them just now. :-)

```yaml
types:
  RamlDataType:
    type: object
    properties:
      propNumber:
        type: number
        format: int32
```

As to using options, raml annotations allow for finer grained control.  I really prefer these :-)
