### ISSUE TITLE
Default value in Jackson's @JsonProperty

### ISSUE THREAD

**Issue by alxgrk** [mulesoft-labs/raml-for-jax-rs#330]
Hi there,

currently there is no handling of default values defined in the RAML, as far as I can see.
However, Jackson offers the possibility to add an annotation attribute `defaultValue` to the `@JsonProperty` annotation. This [will not be used for databinding](https://github.com/FasterXML/jackson-annotations/wiki/Jackson-Annotations), but would then at least be available within the sources.
Could you please add this feature?

Regards,
Alex

**Comment by jpbelang** [comment]
Could you give this a try ?  (3.0.0-SNAPSHOT)
