### ISSUE TITLE
Jackson: Use 'As.EXISTING_PROPERTY' in super types with discriminator

### ISSUE THREAD

**Issue by alxgrk** [mulesoft-labs/raml-for-jax-rs#331]
Hi,

when generating types with Jackson option turned on, the following is generated for types that declare a `discriminator`:

```java
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "type"
)
@JsonSubTypes({
    @JsonSubTypes.Type(B.class)
})
public interface A {
  String getType();
}
```

The subtype `B` overriding the `discriminatorValue` with e.g. `"B"` would then look something like this:

```java
public interface B extends A {
  String getType();

  String getAnotherProp();

  void setAnotherProp(String anotherProp);
}

```

However, if this is getting serialized, the resulting output string will contain the `type` property **twice**, since `@JsonTypeInfo(..., include = As.PROPERTY)` should actually be `@JsonTypeInfo(..., include = As.EXISTING_PROPERTY)`. 

As this is probably the case for every inheritance type structure using `discriminator`, could you please fix this?

Regards,
Alex

**Comment by jpbelang** [comment]
Could you check 3.0.0-SNAPSHOT ?  I can't seem to get the behaviour you are describing.

**Comment by jstoiko** [comment]
3.0 released. Feel free to re-open this issue or create a new one if it doesn't work as expected

**Comment by JoergAdler** [comment]
We are still seeing this behavior wir 3.0.1 Another possible solution would be to add an "@JsonTypeId" to the implementing type.

**Comment by alxgrk** [comment]
Sorry for not responding lately, I just tried it out again as well and obviously the problem still exists...

**Comment by JoergAdler** [comment]
The reason of this behavior is handled in the following merge request. Would be nice, if you woulf consider to merge it.

https://github.com/mulesoft-labs/raml-java-tools/pull/13
