### ISSUE TITLE
Can not Generate Types (Models) for Jackson1

### ISSUE THREAD

**Issue by mikkoi** [mulesoft-labs/raml-for-jax-rs#332]
I try to generate Jackson 1 (Codehaus) annotations. Unfortunately Jackson 2 is not an option. But I get Jackson 2 with the following configuration. Is this a bug?
(And the <jsonMapperConfiguration> optiosn do not seem to work either!)

			<plugin>
				<groupId>org.raml.jaxrs</groupId>
				<artifactId>raml-to-jaxrs-maven-plugin</artifactId>
				<version>2.1.1</version>
				<dependencies>
				</dependencies>
				<configuration>
					<ramlFile>${project.basedir}/src/main/raml/api.raml</ramlFile>
					<removeOldOutput>true</removeOldOutput>
					<resourcePackage>***.resources</resourcePackage>
					<modelPackage>***.json</modelPackage>
					<supportPackage>***.resources.support</supportPackage>
 					<jsonMapper>jackson1</jsonMapper>
 					<jsonMapperConfiguration> 
 						<includeHashcodeAndEquals>true</includeHashcodeAndEquals> 
 						<IncludeJsr303Annotations>true</IncludeJsr303Annotations> 
 						<includeToString>true</includeToString> 
 					</jsonMapperConfiguration> 
 					<generateTypesWith> 
 						<value>jackson</value> 
 						<value>jsr303</value> 
 					</generateTypesWith> 
				</configuration>
				<executions>
					<execution>
						<id>generate-interface-sources-from-raml</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<phase>generate-sources</phase>
					</execution>
				</executions>
			</plugin>

**Comment by jstoiko** [comment]
@mikkoi: can you try `jackson` instead?

In the [docs](https://github.com/mulesoft-labs/raml-for-jax-rs/blob/821cc8864a690864e226a3465e49e27163fe8954/raml-to-jaxrs/examples/maven-examples/simple-json-example/README.md) it says:
> The jsonMapper configuration parameter specifies which annotation strategy should be used by jsonschema2pojo. Available options are jackson, jackson2 and gson

If that's not a bug and was really intended this way, we should probably change `jackson` to `jackson` to make it less ambiguous since `jackson` is an [alias of `jackson2` in jsonschema2pojo](https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/AnnotationStyle.java#L27).

**Comment by mikkoi** [comment]
I tried both `jackson` and `jackson1`. Same result.

org/raml/jaxrs/codegen/maven/RamlJaxrsCodegenMojo.java:
```
  /**
   * The JSON object mapper to generate annotations to: either "jackson1", "jackson2" or "gson" or "none"
   */
  @Parameter(property = "jsonMapper", defaultValue = "jackson2")
  private String jsonMapper;
```

 Jackson2 seems to be default in jsonschema2pojo.
https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/AnnotationStyle.java

**Comment by jpbelang** [comment]
On branch 3.0.0, i've quickly built a jackson1 annotation plugin.  I don't have a setup to check it right now.
It does not du unions right now (I need to check the jackson1 docs to build a custom serializer).

In your maven file ,as a config:

```xml
            <plugin>
                <groupId>org.raml.jaxrs</groupId>
                <artifactId>raml-to-jaxrs-maven-plugin</artifactId>
                <version>${project.version}</version>
                <configuration>
                    <ramlFile>${project.build.resources[0].directory}</ramlFile>
                    <includes>
                        <include>types_user_defined.raml</include>
                    </includes>
                    <resourcePackage>example.resources</resourcePackage>
                    <modelPackage>example.model</modelPackage>
                    <resourcePackage>example.types</resourcePackage>
                    <supportPackage>example.support</supportPackage>
                    <generateTypesWith>
                        <value>jackson1</value>
                    </generateTypesWith>
                </configuration>
            </plugin>
```

**Comment by jpbelang** [comment]
I've put unions in.

**Comment by mikkoi** [comment]
Tested. Works.
Thank you. And sorry for late reply.

**Comment by jpbelang** [comment]
No problem!
