### ISSUE TITLE
NumberFormatException: For input string: "mediaType" When running phases on Array Data Types

### ISSUE THREAD

**Issue by 2324829** [mulesoft-labs/raml-for-jax-rs#336]
When using type "array" (As seen below) I get the following exception

Caused by: java.lang.NumberFormatException: For input string: "mediaType"
        at org.raml.yagi.framework.util.NodeSelector.selectFrom(NodeSelector.java:191)
        at org.raml.yagi.framework.util.NodeSelector.selectFrom(NodeSelector.java:62)
        at org.raml.v2.internal.impl.v10.phase.MediaTypeInjectionPhase.getDefaultMediaTypes(MediaTypeInjectionPhase.java:62)
        at org.raml.v2.internal.impl.v10.phase.MediaTypeInjectionPhase.apply(MediaTypeInjectionPhase.java:44)
        at org.raml.v2.internal.impl.v10.Raml10Builder.runPhases(Raml10Builder.java:114)
        at org.raml.v2.internal.impl.v10.Raml10Builder.build(Raml10Builder.java:93)

After inspecting NodeSelector I see the following code:

           else if (currentNode instanceof ObjectNode)
            {
                currentNode = findValueWithName(currentNode, token);
            }
            else if (currentNode instanceof ArrayNode)
            {
                final int index = Integer.parseInt(token);
                currentNode = findElementAtIndex(currentNode, index);
            }
When I use an object instead of array this works... for both object or array token = "mediaType", for objects the currentNode can be found and mediaType is returned, for arrays (as seen below in my example)  the token=mediaType is used for the node lookup by index of the array, which will always throw this exception. Am I defining array types properly? Please advise.

#%RAML 1.0 DataType
displayName: Documents
description: List of product documents
type: array
items: 
  type: object
  properties:
    docTypeID: 
      type: string
    description:
      type: string 
    docID: 
      type: string
    pin: 
      type: string
    participantType: 
      type: string
    folderID: 
      type: number
    dateReceived: 
      type: datetime
    viewedCounter: 
      type: number
    userDeleted: 
      type: string
    destinationName: 
      type: string
    docLocation: 
      type: string
    additionalDescription: 
      type: string
    emailJobID: 
      type: number
    approved: 
      type: string
    nickName?: 
      type: string
    accountNumber?:
      type: number
      
example: !include ../examples/Documents.raml 

#%RAML 1.0 NamedExample
[  
   {  
      "docTypeID":"test12354",
      "description":"Test Document",
      "docID":"1254T",
      "pin":"testpin",
      "participantType":"testparticipant",
      "folderID":"2333",
      "dateReceived":"2016-02-28T16",
      "viewedCounter":"124578",
      "userDeleted":"Y",
      "destinationName":"Test Destincation",
      "docLocation":"Test Location",
      "additionalDescription":"Test add description",
      "emailJobID":"12457",
      "approved":"Y",
      "nickName":"Vacation Home",
      "accountNumber":"12478"
   },
   {  
      "docTypeID":"test12354",
      "description":"Test Document",
      "docID":"1254T",
      "pin":"testpin",
      "participantType":"testparticipant",
      "folderID":"2333",
      "dateReceived":"2016-02-28T16",
      "viewedCounter":"124578",
      "userDeleted":"Y",
      "destinationName":"Test Destincation",
      "docLocation":"Test Location",
      "additionalDescription":"Test add description",
      "emailJobID":"12457",
      "approved":"Y",
      "nickName":"Vacation Home",
      "accountNumber":"12478"
   }
]

Thoughts?

Thanks

**Comment by 2324829** [comment]
@jpbelang any thoughts? Thanks

**Comment by jpbelang** [comment]
The formatting is gone from your post.  YAML being what it is, I can't make heads or tail of this.

The RAML forum might be a better place to get quicker answers to this stuff.

https://forum.raml.org/

**Comment by 2324829** [comment]
I posted the following, which is my current state on this

https://forum.raml.org/t/assistance-with-array-types-not-generating-model-objects/2172

Thanks for your assistance.
