### ISSUE TITLE
3.0.0 release referring to raml-to-pojo:jar:1.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by aagarwl** [mulesoft-labs/raml-for-jax-rs#340]
Hi,

I was trying to use raml-to-jaxrs-maven-plugin version 3.0.0 for my code and found that is referring to raml-to-pojo:jar:1.0.0-SNAPSHOT internally, but the snapshot version is not available in the respository. 
The error i am getting while running the mvn is : 

Execution GenerateAdminV1 of goal org.raml.jaxrs:raml-to-jaxrs-maven-plugin:3.0.0:generate failed: Plugin org.raml.jaxrs:raml-to-jaxrs-maven-plugin:3.0.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.raml.jaxrs:raml-to-jaxrs-maven-plugin:jar:3.0.0 -> org.raml.jaxrs:jaxrs-code-generator:jar:3.0.0 -> org.raml:raml-to-pojo:jar:1.0.0-SNAPSHOT: Failed to read artifact descriptor for org.raml:raml-to-pojo:jar:1.0.0-SNAPSHOT: Failure to find org.raml:raml-java-tools:pom:1.0.0-SNAPSHOT in http://rms-ch.mspu.hq.k.grp:8081/nexus/content/groups/mspu-public-ch was cached in the local repository, resolution will not be reattempted until the update interval of mspu-repo-ch has elapsed or updates are forced

Could this be looked into and fixed?  Also is there any workaround for now?

**Comment by jpbelang** [comment]
3.0.1 was just released, fixing exactly that issue.

**Comment by aagarwl** [comment]
Thanks for the quick reply.

Using release 3.0.1 i am facing another 'null' error:

[ERROR] Failed to execute goal org.raml.jaxrs:raml-to-jaxrs-maven-plugin:3.0.1:generate (GenerateAdminV2) on project ml-sp-bcm-api: Error generating Java classes from: null: unable to create type array item of type object (or maybe an inline array type ?) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

could you help me out with please?

**Comment by jpbelang** [comment]
Are you trying to create a new type that is an array ? Can you show me a snippet ?  (or the whole thing ?)

**Comment by aagarwl** [comment]
Below is the snippet of the schema that i am try to do:

  contentRating:
    usage: The base type for content ratings
    type: record
    properties:
      code:
        required: true
        type: string
        description: The content rating code. This is unique across all content ratings in the system for a given rating body
      maturityRating:
        required: false
        type: integer
        description: The maturity rating 'bucket' for this content rating
      dvbRating:
        required: false
        type: integer
        description: The DVB equivalent rating for this content rating
      regionalinfo:
        required: true
        type: array
        minItems: 0
        description: Regional information holding locale specific descriptions
        items:
          type: object
          properties:
            locale:
              required: true
              type: locale
            description:
              required: true
              type: string
              maxLength: 256
              description: Locale specific description of the content rating
      logos:
        type: object
        properties:
          preferred:
            type: preferredImage
            description: The preferred image logo URL for this content rating
            required: false
          alternate:
            type: preferredImage
            description: The alternative image logo URL for this content rating
            required: false
      ratingBodyId:
        required: true
        type: recordId
        description: The id of the rating body to which this content rating belongs

  contentRatings:
    usage: The wrapper type for an array of content ratings and the total count of results matching the request
    properties:
      contentRatings:
        required: true
        type: contentRating[]
        description: The collection of content ratings
        minItems: 0
      totalRecords:
        required: true
        type: integer
        description: The total count of results matching the request
        minimum: 0
    type: object

**Comment by jpbelang** [comment]
Could you repost the snippet with formatting ?  Use the markdown formatting strings  it's three backticks followed by "yaml".
```yaml
this:  helps
  with: reading

**Comment by aagarwl** [comment]
Hi,
Attached is the raml file i am facing issue with
[uploaded.zip](https://github.com/mulesoft-labs/raml-for-jax-rs/files/1846604/uploaded.zip)

**Comment by jpbelang** [comment]
Ok, here is the problem:

```yaml
      regionalinfo:
        required: true
        type: array
        minItems: 0
        description: Regional information
        items:
          type: object
          properties:
            locale:
              required: true
              type: locale
            description:
              required: true
              type: string
              maxLength: 256
              description: Locale specific description of the content r
```
You are trying to create an inline array type.  Declare your type separately (in the types section) and declare the property as an array of that type.

That may seem like a pain, but the parser does very little to help us figure out inline types.  That, and a couple of bugs with array type item type declaration make it difficult to figure out the type correctly.

**Comment by jpbelang** [comment]
Track this issue (which is related to parser issues....)
https://github.com/mulesoft-labs/raml-for-jax-rs/issues/337
