### ISSUE TITLE
Is it possible to generate types with JAXB and annotate the types with Jackson annotations?

### ISSUE THREAD

**Issue by 2324829** [mulesoft-labs/raml-for-jax-rs#344]
I'm generating types with jaxb and since types contain an interface and an implementation I am wondering if it is possible to also annotate the types/interfaces with Jackson annotations, so that Jackson can deserialize json if needed? Currently Jackson cannot locate the concrete classes, something like @JsonDeserialize(as=Concrete.class) is needed in the generated interfaces.  Thoughts?

**Comment by jpbelang** [comment]
No, and I doubt it would be possible, as jaxb uses a different code generation library from our code. 

But doesn't jaxb also support json encoding ?

**Comment by jpbelang** [comment]
You might be able to do it through jaxb mechanisms, however.  On those I am not an expert, but maybe around this stuff ?

https://stackoverflow.com/questions/8702559/adding-an-annotation-to-a-jaxb-binding-class-from-a-schema
