### ISSUE TITLE
@Provides annotation missing for @POST

### ISSUE THREAD

**Issue by youac** [mulesoft-labs/raml-for-jax-rs#347]
For the following RAML

```
/postEndpoint:
     responses:
          200:
               body:
                    application/json:
     body:
          application/json:
```
Generates the following code in version 3.0.1
```
@POST
@Path
@Consumes("application/json") 
PostPostEndpointResponse postPostEndpoint() 
```

Previous versions also generated a @Provides("application/json") annotation. Is this also possible on version 3.0.1?

**Comment by jpbelang** [comment]
Oupsie.  My UTs did not check for that (for some reason) and sometimes left empty annotations."

Could you check the 3.0.2 branch ?

**Comment by youac** [comment]
Excellent, that fixes it
