### ISSUE TITLE
wrong JsonFormat pattern for type datetime-only

### ISSUE THREAD

**Issue by blubber88** [mulesoft-labs/raml-for-jax-rs#353]
Hello all,

I've following issue regarding the "datetime-only" type when generating the pojo classes.

My raml file has following entry:
```
	types:
	  Organization:
		properties:
		  id:
			type: number
			format: int64
			required: true
		  modificationTime:
			type: datetime-only
			example: 2015-07-04T21:10:00
```
		

Which generates following java class part:
```
  @JsonProperty("modificationTime")
  @JsonFormat(
      shape = JsonFormat.Shape.STRING,
      pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSZ")
  private Date modificationTime;
```
  
So it would serialize/deserialize following example:
`	"modificationTime": "2015-07-04T21:10:00.000+0200"`

In the[ RAML 1.0 specification](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#date) following is written:

> datetime-only: Combined date-only and time-only with a separator of "T", namely yyyy-mm-ddThh:mm:ss[.ff...]. Does not support a time zone offset.

>   fireworks:
>     type: datetime-only # no implications about offset
>     example: 2015-07-04T21:00:00

Therefore I would expect following pattern in the generated java class (without Offset/Timezone "Z"):
```
  @JsonFormat(
      shape = JsonFormat.Shape.STRING,
      pattern = "yyyy-MM-dd'T'HH:mm:ss")
  private Date modificationTime;
```

I'm using RAML 1.0 with org.raml.jaxrs v: 3.0.1

Thanks for your help on this.

**Comment by jpbelang** [comment]
Looking into it.

**Comment by jpbelang** [comment]
You are correct.  I changed it in raml-java-tools.
