### ISSUE TITLE
raml-to-jaxrs Determines That Legal Version 1.0-complaint RAML Is Not Version 1.0 RAML

### ISSUE THREAD

**Issue by deduper** [mulesoft-labs/raml-for-jax-rs#356]
At my work we have an API that's structured with a whole bunch of included types, traits, libraries and what-have-you,  defined in their own individual RAML files. These include (_no pun intended_) our own project-specific RAML files; plus a bunch more enterprise-mandated shared RAML files. All together there are about sixty RAML files for the one API; including the main base API RAML file...

```
D:/deduper/api/
  |_shared-raml/
  |   |_data-types/ 
  |	 |   +*.raml
  |	 |   +*.raml 
  |	 |_so-forth/
  |	 |   +*.raml
  |      |   +*.raml
  |	 |   +*.raml
  |	 |_etc...
  |_project-raml/
  |      |_data-types/
  |	 |   +*.raml
  |	 |   +*.raml 
  |	 |_what-not/
  |	 |   +*.raml
  |	 |   +*.raml
  |	 |_and-so-on.../
  | +base.raml
```
		 

When I put this through  the raml-to-jaxrs gradle plugin, it fails to generate the JAXRS. The `GenerationException` message is, "_RAML file is neither v10 nor v08 api file_". 

```
buildscript {
  repositories {
    mavenLocal()
    maven { url 'https://repository.mulesoft.org/snapshots/' }
    maven { url 'https://repository.mulesoft.org/releases/' }
    mavenCentral()
  }
  dependencies {
    classpath "org.raml.jaxrs:raml-to-jaxrs-gradle-plugin:3.0.2"
  }
}

apply plugin: 'java'
apply plugin: 'ramltojaxrs'

group = 'deduper'
version = '0.0'

repositories {
     mavenLocal()
     maven { url 'https://repository.mulesoft.org/snapshots/' }
     maven { url 'https://repository.mulesoft.org/releases/' }
     mavenCentral()
}

dependencies {
    compile 'commons-lang:commons-lang:2.3'
}

ramltojaxrs {
    sourceDirectory = file('d:/dedupe/api')
    outputDirectory = new File(buildDir,'generated')
    supportPackageName = 'io.deduper.support'
    resourcePackageName = 'io.deduper.resrc'
    modelPackageName = 'io.deduper.model'
}
```

Because of the sheer number of RAML files involved, plus the super-strict confidentiality I'm legally bound to comply with at work, I can't provide any RAML that reproduces the issue. But I did loosely replicate the raml-to-jaxrs code that throws the `GenerationException`....

```
import org.raml.v2.api.*;
import org.raml.v2.api.loader.*
import org.apache.commons.io.FileUtils;
import java.util.Collection;
import java.io.File;
import org.jsonschema2pojo.AnnotationStyle;
import org.raml.jaxrs.generator.*;
...
Configuration generatorConfig = new Configuration();

File baseRamlFile = new File("D:/deduper/api/base.raml"); 

String[] fileExtensions = {"raml", "yaml"};

Collection<File> ramlFiles = FileUtils.listFiles(new File(baseRamlFile.getParent()), fileExtensions, true);

public static void scan(Collection<File> ramlFiles, Configuration config){ 

	 RamlScanner scanner = new RamlScanner(config);
	 
	 for(File raml : ramlFiles) { 
	     try{scanner.handle(raml); }
	     catch(GenerationException | IOException geioe){
                 System.err.println(raml.getAbsolutePath() +  " scanned as '" + geioe.getMessage() + "'");					 
	      }
	 } 	
}

public static void main(String...args){ 
    ...
    scan(ramlFiles, generatorConfig);
    ...
}

```
What I can tell you however, is that - _on top of  the RAML successfully passing my work's internal validation checks_ - running the RAML through the following code, I have established that there are not any "_errors_" in the RAML. But for some reason (_I have no idea why_) raml-to-jaxrs does not recognize fifty-nine out of sixty RAML files as version 1.0 RAML...

```
...
public Api validate(File raml){ 

   String ramlPath = raml.getAbsolutePath();
   Api api = null;
   RamlModelResult ramlModelResult = new RamlModelBuilder( ).buildApi(raml);
    if(ramlModelResult.hasErrors( )){
        System.out.printf ("Validation failed for file '%s'.", ramlPath);
	for(ValidationResult validationResult : ramlModelResult.getValidationResults()) {
	    System.out.println(validationResult.getMessage()); 
	}
     }
     else {
         api = ramlModelResult.getApiV10();
     }
     return api;
}
...

public static void main(String...args) {
    ...
   for( File raml : ramlFiles ){
        Api api = validate(raml); 
        System.out.println(ramlPath + " is " + api);
    }
    ...
}
...
```

Running the sixty RAML files through the above code, no validation errors are reported. However, only the base RAML file is printed as "_...base.raml is org.raml.v2.internal.impl.commons.model.Api@6e38784d_". All the remaining fifty-nine are printed as "_.../such-and-such/*.raml is null..._".

_**Why does raml-to-jaxrs determine that my well-formed, independently-established legal version 1.0 RAML is not version 1.0 RAML?**_

If I put the exact same RAML through the _raml-to-jaxrs-cli_, that tool correctly accepts the same RAML as version 1.0. Unfortunately, it then goes on to fail with the `array` type error described in #355.

**Comment by jpbelang** [comment]
Just so I understand this:  the gradle plugin fails, but the same code succeeds with the cli ?  Does the maven plugin pass ?  (I'll try to build a small gradle example with an include to see if I can get it to fail.....)

**Comment by deduper** [comment]
Thank you @jpbelang for looking into this.

And apologies for the delayed reply. Been snowed under at work. In fact, I only have a couple minutes to spare right now. So I'll just reply to a couple things for now, and get back to you with more details and questions.

> "_...the gradle plugin fails, but the same code succeeds with the cli ?..._"

Yup. That's correct. I'm afraid I only vaguely recall checking that the maven plugin works with the same RAML. But, I'm like 85% sure that's what I established. However, when I have more time, I will double check that.


> "_...This scans the whole directory to generate all the files. If you have Raml Libraries in there, it will fail..._"

I looked at the code you're referring to. By "_whole directory_" you mean all of the sub-directories of the directory passed into the `sourceDirectory` argument. That's what I observed in the code, anyway.


> "_...the nulls you were getting for the 59 other files were due to the fact they were not loaded, as they were libraries..._"

Why are you ignoring libraries? That comes as a surprise to me. **_All_** of our data types (_domain objects_) are defined in libraries (_both project-specific ones and enterprise-wide, architecturally-mandated ones_) and included into the base API RAML in which the resources are defined. Surely our shop isn't the only one that follows the "_define-every-data-type-in-external-libraries-and-include-them-where-needed_" approach. The rationale is "_reuse_". Is that really that uncommon a use case?


> "`sourcePaths = files('src/main/resources/xml-model.raml')`"

I saw in the code and in the maven plugin examples where `sourcePaths` was defined. And I thought, "_Hey now! That's exactly what I need!" But when I tried using it in my build.gradle with the gradle plugin, I got an error saying there is no such argument as `sourcePaths` for the gradle plugin.

I will try your latest SNAPSHOT build and get back to you with more details soon. I expect even if this issue is resolved, I will still run into the #355 issue again though. Thanks again for looking into this, @jpbelang.

**Comment by jpbelang** [comment]
> And apologies for the delayed reply. Been snowed under at work
No worries. 

> Why are you ignoring libraries? That comes as a surprise to me. All of our data types (domain objects) are defined in libraries (both project-specific ones and enterprise-wide, architecturally-mandated ones) and included into the base API RAML in which the resources are defined. Surely our shop isn't the only one that follows the "define-every-data-type-in-external-libraries-and-include-them-where-needed" approach. The rationale is "reuse". Is that really that uncommon a use case?

I may have been unclear:  The API you used loads _APIs_.  It needs to be annotated at the top with a "#%RAML 1.0" annotation.  If it's annotated with a "#%RAML 1.0 Library" annotation, that call won't load them (hence the nulls, I suspect).  I'm not sure there is a way, from the RAML parser to load a naked library.

From a given API, the "uses:" directive loads these libraries (as libraries, or overlays, or fragments...).

For the record, this is handled by the raml-parser-2 project, of which I am a user and not a developper.

> I will still run into the #355 issue again though

I have a plan for working on declaring array types this weekend.  It's a complicated issue though and might require  mucking around private APIs in the said parser to get a straight answer.  I'll keep you posted.

**Comment by deduper** [comment]
Thanks again @jpbelang for getting back,

I have had a chance yet to try out your SNAPSHOT. I wanted to finish answering your earlier questions first.

> "..._the nulls you were getting for the 59 other files were due to the fact they were not loaded, as they were libraries_..."

That's the thing though. They're not all libraries. This is the breakdown of the 60 RAML files in our API...

`#%RAML 1.0 Library` - _**6**_
`#%RAML 1.0 Trait` - _**20**_
`#%RAML 1.0 DataType` - _**32**__
`#%RAML 1.0 SecurityScheme` - _**1**_
`#%RAML 1.0 ` - _**1**_ (_Base API RAML_)

 > "..._The API you used loads APIs_..."
 
 I'm afraid I don't catch your meaning, @jpbelang. The majority of the RAML files are `DataType`s. The `Trait`s are the second largest in number.  Obviously that doesn't make a difference to the outcome. Is it  that if the parser finds even one `#%RAML 1.0 Library` file, it spoils it for the rest of the bunch?

The six libraries `!include` those `#%RAML 1.0 DataTypes`. And our base API RAML file (_where the resources are defined_) `uses:` the libraries and traits.

Though the following informational example is obviously contrived,  our RAML is structured more or less like this...

----

_../deduper-libs/model/peanutbutter.raml:_

----


`#%RAML 1.0 DataType`
`type: object`
`description: 100% Peanuts; Crunchy; No added sugar`
`properties:`
`   brand:`
`      type: string`
        `...`

----

_lib/favefoods.raml:_

----


`#%RAML 1.0 Library`
`usage: A generic No-Op example of a deduper API library definition`
`types:`
`   Peanutbutter !include ../deduper-libs/model/peanutbutter.raml`
`   Jam !include ../deduper-libs/model/jam.raml`
`	 Jelly !include ../deduper-types/jelly.raml`
`	 Marmalade !include ../deduper-types/marmalade.raml`
`	 Bread !include  ../deduper-types/bread.raml`


----

_deduper-api.raml:_

----

`#%RAML 1.0`
`...`
`baseUri: http://dediper.api.io/mungry`
`...`
`uses: faves: lib/favefoods.raml`
`...`
`/favoritefoods:`
   `post:`
	    `body:`
`			   type: faves.PeanutButter`
				 `...`

----

> "..._I'm not sure there is a way, from the RAML parser to load a naked library_..."

Have you figured out why the raml-to-jaxrs-cli tool and the maven plugin both handle those naked libraries perfectly fine, but the gradle plugin doesn't?  By the way, I have confirmed that the maven plugin (_v3.0.2; the most recent version in my work's internal repo_) works, insofar as it seems to get past the "_RAML file is neither v10 nor v08 api file_" issue I'm reporting here. However, it then runs into the #355 array issue. 

Many thanks.

**Comment by jpbelang** [comment]
I'll look into the details, if it's still necessary.  But my original idea is still the one that explains it:  

The parser (which I don't own) can only handle APIs *and the files APIs include as part of their parsing*.  If your topmost file is a library, the parser will ignore them.  If the parser ignores them, then I don't see them.
