### ISSUE TITLE
The generated multiPart/form-data source code does not work

### ISSUE THREAD

**Issue by RimShao** [mulesoft-labs/raml-for-jax-rs#363]
Hi ,

We are using the raml to jaxrs to generate the source code:
===Raml===
  post:
    body:
      multipart/form-data:
        properties:
          text: string
          Filter:
            type: file
            fileTypes: ['application/json']
          File:
            type: file
            fileTypes: ['application/zip']
===Jaxrs Source code===
PostValidatorResponse postValidator(ValidatorPostMultipartFormData entity);

public interface ValidatorPostMultipartFormData {
.....
}

And we runing the source code in the Jersey, the HTTP post request does not even been dispatched to the generated interface postValidator.

Then we skip the RAML to Jaxrs plugin, and implement the interface source code directly like below:
public PostValidatorResponse postValidator(
            @FormDataParam("filter") InputStream filterstream,
            @FormDataParam("filter") FormDataContentDisposition filterDetail,
            @FormDataParam("file") InputStream fileStream,
            @FormDataParam("file") FormDataContentDisposition fileDetail);

Then it works.

So question: do you know how we generate the multipart/form-data RAML to the working source source like above.  the point is if we don't have @FormDataParam,  the multipart feature can't work.

Thanks and looking forward your reply.

**Comment by jpbelang** [comment]
I'm at work right now, but from the top of my head: do you have the _Jersey_ multipart dependency in the classpath?

**Comment by RimShao** [comment]
yes,  I import the multipart dependency, and I register MultiPartFeature, and nothing works.

**Comment by jpbelang** [comment]
I have pushed a co.mit with an example of multipart that works for me.

Could you please look at that?

**Comment by RimShao** [comment]
yes thanks, I am trying running gradle with provided maven example. haven't succeeded but will come back if I have progress or new problem.

**Comment by RimShao** [comment]
Thanks a lot. now it works by reference your given example.
