### ISSUE TITLE
The mulitpart/form-data code can NOT be generated if define with "string" type in the raml

### ISSUE THREAD

**Issue by RimShao** [mulesoft-labs/raml-for-jax-rs#373]
https://github.com/mulesoft-labs/raml-for-jax-rs/blob/0344116cbb3f8259425a6b9e4575cee62276abed/raml-to-jaxrs/jaxrs-code-generator/src/main/java/org/raml/jaxrs/generator/extension/resources/JerseyMultipartFormDataResourceExtension.java#L90

**Comment by RimShao** [comment]
Hi, 
I have one problem related above.
I define the below raml, the "string" and "boolean" parameters can not generated into source code. Can you please have a look? Thanks.

      multipart/form-data:
        type: object
        properties:
              deviation:
                  type: string        
              feature:
                  type: string
              keypattern:
                  type: boolean  
              mergecases:
                  type: boolean                                                            
              configuration:
                  type: file
              file:
                  type: file

  @POST
  @Consumes("multipart/form-data")
  PostProcessorJsonschemaResponse postProcessorJsonschema(
                  @FormDataParam("configuration") InputStream configurationStream, 
                  @FormDataParam("configuration") FormDataContentDisposition configurationDisposition, 
                  @FormDataParam("file") InputStream fileStream, 
                  @FormDataParam("file") FormDataContentDisposition fileDisposition);

**Comment by jpbelang** [comment]
I'll look into it on the week-end.  Is this supported by the Jersey plugin ?

**Comment by RimShao** [comment]
Hi,

the generated source code should like below. and it works in Jersey framework.

PostProcessorJsonschemaResponse postProcessorJsonschema(
@FormDataParam("deviation") List<String> deviation,		  
@FormDataParam("feature") List<String> feature,
@FormDataParam("keypattern") boolean keypattern,
@FormDataParam("mergecases") boolean mergecases, 
@FormDataParam("configuration") InputStream configStream, 
@FormDataParam("configuration") FormDataContentDisposition configDisposition, 
@FormDataParam("file") InputStream fileStream, 
@FormDataParam("file") FormDataContentDisposition fileDisposition)

**Comment by jpbelang** [comment]
Done.  All fixed.  Don't go look at the fix. It's embarrassing. :-)

**Comment by RimShao** [comment]
thanks. now it is fixed.
