### ISSUE TITLE
Missing empty constructor for model classes

### ISSUE THREAD

**Issue by vennekilde** [mulesoft-labs/raml-for-jax-rs#377]
I pulled the latest jaxb-example project (3.0.4-SNAPSHOT) and attempted to run it. It launches just fine, however i get the following error when attempting to store a new animal with the rest interface

`java.lang.RuntimeException: Exception [EclipseLink-63] (Eclipse Persistence Services - 2.6.0.v20150309-bf26070): org.eclipse.persistence.exceptions.DescriptorException|Exception Description: The instance creation method [example.model.Animal.<Default Constructor>], with no parameters, does not exist, or is not accessible.|Internal Exception: java.lang.NoSuchMethodException: example.model.Animal.<init>()|Descriptor: XMLDescriptor(example.model.Animal --> [DatabaseTable(Animal)])`

**REST Call**
PUT /animals/bob

**Body**
```
<Animal>
	<animalType>Mammal</animalType>
	<specimenName>Dog</specimenName>
	<gender>male</gender>
</Animal>
```

**Reproducible curl command**
```
curl -X PUT \
  http://localhost:9998/animals/bob \
  -H 'Content-Type: application/xml' \
  -d '<Animal>
	<animalType>Mamal</animalType>
	<specimenName>Dog</specimenName>
	<gender>male</gender>
</Animal>'
```

From what i can understand, it appears that jetty requires that a default constructor is available for each of the model objects, however i also assume this problem would have been noticed by others already, so i am currently at a loss as to what i am doing wrong.

**Comment by jpbelang** [comment]
I'll check this week for sure (things have been intense at work).

**Comment by jpbelang** [comment]
It seems to be having trouble with unions.  Removing the ancestor union works.
```xml
<Animal xmlns:ns0="foo.bar" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="animalImpl">
    <animalType>Dog</animalType>
    <gender>female</gender>
    <mother xsi:type="insectImpl">
        <animalType>Insect</animalType>
        <gender>other</gender>
        <icky>true</icky>
    </mother>
    <siblings xsi:type="animalImpl">
        <animalType>Cat</animalType>
        <gender>female</gender>
    </siblings>
    <siblings xsi:type="insectImpl">
        <animalType>Insect</animalType>
        <gender>other</gender>
        <icky>true</icky>
    </siblings>
</Animal>
```
I'm still looking into it.

**Comment by jpbelang** [comment]
It broke when I made union types into interfaces and implementations.  It seems that moxy won't 
go into things that look like interfaces.  Still figuring it out.
