### ISSUE TITLE
Datetime format misses an ISO8601/RFC3339 format?

### ISSUE THREAD

**Issue by wied03** [mulesoft-labs/raml-for-jax-rs#382]
Maybe I've just been looking at this for too long but I think the wrong JsonFormat is getting generated going from RAML 1.0 to JAXRS code via the Maven plugin (version 3.0.4). If I have a `datetime` using the standard RFC3339 format, then I could have a value like `2018-12-12T00:00:00-08:00`.

The generated code I'm seeing though is this:
```java
@JsonFormat(
      shape = JsonFormat.Shape.STRING,
      pattern = "yyyy-MM-dd'T'HH:mm:ssZ"
  )
  @JsonProperty("deactivate_date")
  private Date deactivateDate;
```
Jackson can't convert with that format given the input example above (which coincidentally is what Mule 4.1's DW is returning). Should the Z be XXX ? https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html seems to imply that for cases when the offset has hours and minutes separated by a colon.

RAML:

```raml
#%RAML 1.0 Library

types:
  Vehicle:
    type: object
    properties:
      card_number:
        type: string
        description: Vehicle's card number
      vehicle_code:
        type: string
        description: The infor Vehicle code
      deactivate_date:
        type: datetime
        description: Date the card will be deactivated
    example:
      card_number: "2003"
      vehicle_code: "9620.11"
      deactivate_date: 2018-12-12T00:00:00-08:00
```

Maven config:
```xml
<plugin>
    <groupId>org.raml.jaxrs</groupId>
    <artifactId>raml-to-jaxrs-maven-plugin</artifactId>
    <version>3.0.4</version>
    <configuration>
        <outputDirectory>${jaxrs.source.generated}</outputDirectory>
        <generateTypesWith>
            <value>jackson</value>
        </generateTypesWith>
    </configuration>
    <executions>
        <execution>
            <id>ourClasses</id>
            <goals>
                <goal>generate</goal>
            </goals>
            <phase>generate-test-sources</phase>
            <configuration>
                <ramlFile>src/main/resources/api/inforsystemapi.raml</ramlFile>
                <modelPackage>${project.groupId}.ramljaxrs.ourapi.models</modelPackage>
                <resourcePackage>${project.groupId}.ramljaxrs.ourapi.types</resourcePackage>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by jpbelang** [comment]
Looking into in now.

**Comment by jpbelang** [comment]
I'll have to generate a serializer, I think.  The default jackson behaviour accepts too many formats and the configuration I used is a bit too narrow.  I'll have something tomorrow/tuesday.

Dammit.  I hate dates.  I also don't like character encodings. :-)
I won't change the output.  Is that an issue ?

**Comment by jpbelang** [comment]
Fixed.  The output form is "yyyy-MM-dd'T'HH:mm:ss.SSSXXX".

The input form is done through a custom deserializer, where I delegate to jackson's StdDateFormat.  This forces me (and the user :-) ) to upgrade to jackson 2.9.2 (2.9.1 had a fractional timezone issue).

By using StdDateFormat, I accept a broader set of values than what is allowed in the RFC, which I'm OK with, following Postel's law.

**Comment by wied03** [comment]
I think this will work
