### ISSUE TITLE
Gradle „Could not find method sign()“ for raml-to-jaxrs-gradle-plugin

### ISSUE THREAD

**Issue by deduper** [mulesoft-labs/raml-for-jax-rs#395]
**raml-for-jax-rs** 3.0.5-SNAPSHOT
**OS**: Windows 7
**Gradle**: v4.7
**Maven**: v3.5.2
**Java runtime**: Oracle OpenJDK Runtime Environment 1.8.0_161-1-ojdkbuild-b14
**Java VM** : Oracle OpenJDK 64-Bit Server VM 25.161-b14 (mixed mode)

Is it intentional that the [_raml-to-jaxrs-gradle-plugin_](https://github.com/mulesoft-labs/raml-for-jax-rs/tree/master/raml-to-jaxrs/raml-to-jaxrs-gradle-plugin) cannot be built independently of the top-most parent project?

**Steps To Reproduce**

1. Navigate to the [_raml-for-jax-rs_](https://github.com/mulesoft-labs/raml-for-jax-rs) github repo
2. Click the green [_Clone or download_](https://github.com/mulesoft-labs/raml-for-jax-rs/archive/master.zip)  dropdown and select [_Download zip_](https://github.com/mulesoft-labs/raml-for-jax-rs/archive/master.zip)
   - Save it
   - Unzip it
   - `cd` to `${install_dir}/raml-for-jax-rs-master/`
3. Type `mvn -DskipTests=true install` 
4. On successful completion of the Maven build, `cd` to `${install_dir}/raml-for-jax-rs-master/raml-to-jaxrs/raml-to-jaxrs-gradle-plugin`   
5. Type `gradle -DartifactVersion=3.0.5-SNAPSHOT check`

**Expected Result**

1. Successful completion of the Gradle `check` task, with Gradle reporting:

    `BUILD SUCCESSFUL in [N]s`

   
**Actual Result**

1. Failure of the Gradle `check` task, with Gradle reporting:

`FAILURE: Build failed with an exception.`

`* Where:`
`Build file 'G:\mulesoft-labs\raml-for-jax-rs-master\raml-to-jaxrs\raml-to-jaxrs-gradle-plugin\build.gradle' line: 232`

`* What went wrong:`
`A problem occurred evaluating root project 'raml-to-jaxrs-gradle-plugin'.`
`> Could not find method sign() for arguments [org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication_Decorated@3a489536] on object of type org.gradle.plugins.signing.SigningExtension.`
`...`
`* Exception is:`
`org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'raml-to-jaxrs-gradle-plugin'.`
 `  ...   `
`Caused by: `
`org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: `
`Could not find method sign() for arguments` `[org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication_Decorated@22af99ec] on object of type org.gradle.plugins.signing.SigningExtension.`
`at` `org.gradle.internal.metaobject.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java`
`  ...`    
`BUILD FAILED in [N]s`

**_NB_**: _The same failure results when attempting any Gradle task in that project, by the way; not just the `check` task_.

--

[_**Download full stack trace**_](https://github.com/mulesoft-labs/raml-for-jax-rs/files/2959001/raml.to.jaxrs.gradle.plugin.issue.395.gradle.build.stack.trace.1.txt).

**Comment by jpbelang** [comment]
I've redone the gradle build because of publication problems with Travis. Is this working in 3.0.6?

**Comment by deduper** [comment]
Hey @jpbelang . Yeah. Reran that `gradle check` and it checks out fine now. Thanks.

While awaiting your reply a couple weeks ago though, I tried to troubleshoot it myself. The `gradle.taskGraph.whenReady { taskGraph -> ...}` block in the original `build.gradle` made me curious. 

So I provided my own specific values for the `GPG_xxx` environment variables that block requires. I also replaced the hard-coded `"0BC1B7B9"` key id with my own OpenPGP public key id. Then, while in the same `raml-to-jaxrs-gradle-plugin` sub-project folder, I ran `gradle -DartifactVersion=3.0.5 publishMavenJavaPublicationToMavenRepository` and got:

    
    > Task :publishMavenJavaPublicationToMavenRepository
    Could not transfer artifact org.raml.jaxrs:raml-to-jaxrs-gradle-plugin:jar:3.0.5 from/to remote (https://oss.sonatype.org/service/local/staging/deploy/maven2/): Could not write to resource 'org/raml/jaxrs/raml-to-jaxrs-gradle-plugin/3.0.5/raml-to-jaxrs-gradle-plugin-3.0.5.jar'
    Could not transfer artifact org.raml.jaxrs:raml-to-jaxrs-gradle-plugin:pom:3.0.5 from/to remote (https://oss.sonatype.org/service/local/staging/deploy/maven2/): Could not write to resource 'org/raml/jaxrs/raml-to-jaxrs-gradle-plugin/3.0.5/raml-to-jaxrs-gradle-plugin-3.0.5.pom'
    Could not transfer artifact org.raml.jaxrs:raml-to-jaxrs-gradle-plugin:jar:sources:3.0.5 from/to remote (https://oss.sonatype.org/service/local/staging/deploy/maven2/): Could not write to resource 'org/raml/jaxrs/raml-to-jaxrs-gradle-plugin/3.0.5/raml-to-jaxrs-gradle-plugin-3.0.5-sources.jar'
    Could not transfer artifact org.raml.jaxrs:raml-to-jaxrs-gradle-plugin:jar:javadoc:3.0.5 from/to remote (https://oss.sonatype.org/service/local/staging/deploy/maven2/): Could not write to resource 'org/raml/jaxrs/raml-to-jaxrs-gradle-plugin/3.0.5/raml-to-jaxrs-gradle-plugin-3.0.5-javadoc.jar'
    Could not transfer artifact org.raml.jaxrs:raml-to-jaxrs-gradle-plugin:jar.asc:sources:3.0.5 from/to remote (https://oss.sonatype.org/service/local/staging/deploy/maven2/): Could not write to resource 'org/raml/jaxrs/raml-to-jaxrs-gradle-plugin/3.0.5/raml-to-jaxrs-gradle-plugin-3.0.5-sources.jar.asc'
    Could not transfer artifact org.raml.jaxrs:raml-to-jaxrs-gradle-plugin:jar.asc:javadoc:3.0.5 from/to remote (https://oss.sonatype.org/service/local/staging/deploy/maven2/): Could not write to resource 'org/raml/jaxrs/raml-to-jaxrs-gradle-plugin/3.0.5/raml-to-jaxrs-gradle-plugin-3.0.5-javadoc.jar.asc'
    Could not transfer artifact org.raml.jaxrs:raml-to-jaxrs-gradle-plugin:pom.asc:3.0.5 from/to remote (https://oss.sonatype.org/service/local/staging/deploy/maven2/): Could not write to resource 'org/raml/jaxrs/raml-to-jaxrs-gradle-plugin/3.0.5/raml-to-jaxrs-gradle-plugin-3.0.5.pom.asc'
    Could not transfer artifact org.raml.jaxrs:raml-to-jaxrs-gradle-plugin:jar.asc:3.0.5 from/to remote (https://oss.sonatype.org/service/local/staging/deploy/maven2/): Could not write to resource 'org/raml/jaxrs/raml-to-jaxrs-gradle-plugin/3.0.5/raml-to-jaxrs-gradle-plugin-3.0.5.jar.asc'
    
    > Task :publishMavenJavaPublicationToMavenRepository FAILED
    
    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':publishMavenJavaPublicationToMavenRepository'.
    > Failed to publish publication 'mavenJava' to repository 'maven'
       > Could not write to resource 'https://oss.sonatype.org/service/local/staging/deploy/maven2/org/raml/jaxrs/raml-to-jaxrs-gradle-plugin/3.0.5/raml-to-jaxrs-gradle-plugin-3.0.5.jar'.
          > Could not PUT 'https://oss.sonatype.org/service/local/staging/deploy/maven2/org/raml/jaxrs/raml-to-jaxrs-gradle-plugin/3.0.5/raml-to-jaxrs-gradle-plugin-3.0.5.jar'. Received status code 403 from server: Forbidden
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    
    * Get more help at https://help.gradle.org

    BUILD FAILED in 1m 37s
    8 actionable tasks: 8 executed
    

***NB***: Notice that I used `-DartifactVersion=3.0.5` that time.

Same deal when giving gradle the more recent `build-sonatype.gradle`. I think I know why it failed. Probably because my specific OSSRH and NEXUS credentials aren't allowed to publish stuff to your `org.raml` group space? Or maybe because there is already an existing, previously-published artifact with the same group id, artifact id and version in OSS/NEXUS? Right?

So what I'm curious about is not so much „_Why does it fail?_“. What I am curious to understand, is _What is the intended use case for that `GPG_xxx` part of the build script_?“ TIA :)
