### ISSUE TITLE
Java 11+ Support?

### ISSUE THREAD

**Issue by deduper** [mulesoft-labs/raml-for-jax-rs#398]
Hey @jpbelanger? I've forked [_pojo-to-raml release/1.0.6_](https://github.com/deduper/raml-java-tools/tree/feature/Support.Java9+/pojo-to-raml) and [_raml-for-jax-rs release/3.0.6_](https://github.com/deduper/raml-for-jax-rs/tree/feature/Support.JDK.12%2B) to get them to support being built by and run in Java 9 and higher.

I can appreciate if supporting Java 11 isn't an immediate priority for your projects right now. I see nobody here is clamoring for it :) But a project I'm working on called for it. So I took a stab at it and thought I'd  share what I've learned so far.

I was very conscious to only change the minimum necessary to make things build successfully.  No Jigsaw modular support. So the majority of changes are mainly to build scripts. The forks are upgraded to newer versions of four or five Maven plugins, for example.

You're probably aware that one of the most common snags when migrating to Java 9+, is pre-9 code that uses class loaders in any way. 

I introduced [_one new helper class_](https://github.com/deduper/raml-java-tools/tree/feature/Support.Java9%2B/pojo-to-raml/src/main/java/org/raml/pojotoraml/util) (_with unit tests_) to address class loading issues that arose in [_two classes of pojo-to-raml_](https://github.com/deduper/raml-java-tools/commit/b02781d4be2fbab4c01e8b678133c61d05de800d).

I also addressed a little-known — but prevalent — „[_master bug_](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8075793)“ in Java itself. The bug lies dormant in code targeted for older, pre-9 builds of javac. It showed up in [_one test class of jaxrs-parser_](https://github.com/deduper/raml-for-jax-rs/tree/feature/Support.JDK.12%2B/jaxrs-to-raml/jaxrs-parser/src/test/java/org/raml/jaxrs/parser/analyzers). The fix was minor. But it's guaranteed to work in the older buggy javacs and in 9 and higher.

So far, I've been able to successfully build both forks with JDK 11 and 8 on Windows and JDK 12 and 8 on Linux. Importantly, all of the unit tests pass. I have also successfully used the Java 11-/12-built raml-to-jaxrs-maven plugin.

Pojo-to-raml was the only dependency from that project that was absolutely necessary to modify. But again, a minor change. The forked artifact has been [_published to Maven Central_](https://mvnrepository.com/artifact/io.github.deduper/pojo-to-raml-jdk12). It's configured as a dependency in a couple of the forked raml-for-jax-rs sub-modules.

Maybe you'll get some spare time to code review [_the raml-for-jax-rs fork_](https://github.com/deduper/raml-for-jax-rs/tree/feature/Support.JDK.12%2B)? 

I look forward to any feedback.

**Comment by jpbelang** [comment]
Swear to god, reviewed on the weekend.

In the near future, we will be moving to the new amf parser, and we will be upgrading the java version, so any insight you've had will help us.

Thanks.

**Comment by deduper** [comment]
Hey now! :) It's pretty neat that you guys approved of the JDK 9+ updates :+1: Thanks for going to bat for me @jpbelang!

I had a look at the [_AMF parser_](https://github.com/aml-org/amf) deal I think you are referring to. Looks like it will be an awesome improvement. What's the ETA on migration to that? Roughly?

**Comment by jpbelang** [comment]
No problem. It still needs to compile Java7, but we're almost done with that version.  I'll take any help that moves this forward :-)

As to amf and friends, I'm working on it this month.
