### ISSUE TITLE
Error generating Java classes from raml-to-jaxrs-maven-plugin

### ISSUE THREAD

**Issue by diggernet** [mulesoft-labs/raml-for-jax-rs#405]
Version: 3.0.0 and later (worked in 2.1.1).
Scenario: Define a type with a name ending with "`Response`", and containing a property with a type which is an object with a discriminator.
Error: `[ERROR] Failed to execute goal org.raml.jaxrs:raml-to-jaxrs-maven-plugin:3.0.5:generate (default) on project [projectName]: Error generating Java classes from: null: can't fetch type named [propertyName]`
(Where `[projectName]` is the name of the maven project, and `[propertyName]` is the name of the first property in the type which has a type with a discriminator.)

Changing the name of `PetResponse` to `Petresponse` or `PetResponseType` (or pretty much anything else) avoids the error.  As does defining `Animal` without a discriminator.

test.raml:

	#%RAML 1.0 Library
	
	types:
	  PetResponse:
	    type: object
	    properties:
	      myPet:
	        type: Animal
	
	  Animal:
	    type: object
	    discriminator: animalType
	    properties:
	      animalType: string
	
	  Cat:
	    type: Animal
	    discriminatorValue: CAT
	    properties:
	      legs: integer
	
	  Fish:
	    type: Animal
	    discriminatorValue: FISH
	    properties:
	      fins: integer

**Comment by jpbelang** [comment]
Looking into it today.

**Comment by rspremulli-sf** [comment]
This issue is impacting us as well. If there is any further progress you made debugging this, please share.

**Comment by diggernet** [comment]
This was fixed in v3.0.7.  Thanks!
