### ISSUE TITLE
XSD global types and elements in RAML -> JAX RS - which is chosen as parameter?

### ISSUE THREAD

**Issue by northlander** [mulesoft-labs/raml-for-jax-rs#43]
If I generate jax-rs from RAML with XSD embedded with global types and one global element, it chooses (randomly?) one of the types as parameter. In the following example, it seems to choose MyType2 as parameter to the post method. 

How to force RAML -> JAX-RS to use the root element or is it even possible without nesting the types under the element?

```
body:
        application/xml:
            schema: |
                <?xml version="1.0" encoding="UTF-8"?>
                <xs:schema xmlns ...
                <xs:element name="MyRootElement" type="MyType3"/>
                <xs:complexType name="MyType1" ..
                <xs:complexType name="MyType2" ..
                <xs:complexType name="MyType3" ..
```

**Comment by petrochenko-pavel-a** [comment]
There i no way to do it currently, I will try to add it asap.

Regards,
Pavel

**Comment by BackendButters** [comment]
Is there any update on this?

**Comment by jpbelang** [comment]
Does this work in 2.0 ?
