### ISSUE TITLE
How to handle Authentication?

### ISSUE THREAD

**Issue by talios** [mulesoft-labs/raml-for-jax-rs#44]
Whats the best way to handle authentication with raml-for-jax-rs, currently it doesn't look like the `securitySchemes:` part of RAML is (currently) supported, so I'm using:

```
traits:
  - secured:
      headers:
          Authorization:
              description: |
                 Used to send a base64 encoded access token.
              type: string
      responses:
        401:
          description: Authentication token MUST be provided.
        403:
          description: The authenticated user has insufficient authorisation for this resource.
```

this generates `@HeaderParam("Authorization") String authorization` as an argument in the Jax-RS methods, and then I have some custom code takes the header value, a failure response and a lambda and parses the header content, processing the lambda if valid:

```
public static <T> T withAuth(String authorisation, T forbiddenResponse, Function<UserReference, T> fn)
```

and called:

```
return withAuthTransaction(authorization, SomeResponse.withForbidden(), userReference -> {
  ....
}
```

Is there a better solution than this?  At least as far as the parsing of the Authorisation header is concerned?

**Comment by petrochenko-pavel-a** [comment]
Actually authentification is usually processed in interceptors (this is why it is out of scope of sceleton generation). What looks logical to me is to add support for generating interceptors but this field has really lot of possible options. 

Regards,
Pavel

**Comment by ddossot** [comment]
Agreed with @petrochenko-pavel-a , there are many different ways to secure JAX-RS resources, it's better to leave it to the implementer to deal with it.
