### ISSUE TITLE
Support including UriInfo in request methods

### ISSUE THREAD

**Issue by talios** [mulesoft-labs/raml-for-jax-rs#46]
Is there anyway currently to support the generation of JAX-RS methods that include `@Context UriInfo uriInfo` as an argument from within a RAML document?

This is needed to that I can call `uriInfo.getAbsolutePath()` to get the path of the current request so inclusion in custom representation generation.

Is this currently supported by raml-for-jax-rs?

**Comment by petrochenko-pavel-a** [comment]
Currently it is not supported, but it is pretty simple to add as an option. But you probably do not want to add it to all your methods, so we have to think about how to mark methods that needs which needs context parameters. I am thinking about providing extra file with configuration/annotations for your raml or about specially named traits to mark. Actually first option looks better for me as more generic. 

Do you have any other ideas about possible implementation?

Regards, Pavel.

**Comment by ddossot** [comment]
The intention was in fact that you would use class variables for these extra contextual fields. No need to add them into the methods.

**Comment by petrochenko-pavel-a** [comment]
Smart idea. Together with security it probably needed to be added to
something like FAQ section in the documentation. But still i think we may
support it with coming of metadata in RAML 1.0(if it will be there)

Regards,
Pavel
06 Мар 2015 г. 15:53 пользователь "David Dossot" <notifications@github.com>
написал:

**Comment by talios** [comment]
@ddossot class variables?  That sounds rather non-thread safe, unles they're `ThreadLocal`s? For the record, I actually kinda _do_ want it on _every_ method, as I'm wanting to return a HAL document/representation using my HalBuilder library, and want to include the `self` link back to the calling URI.

Tho this probably really calls out for more control on supporting return types, currently the project supports JSON Schema using and the pojo generator. Maybe I want to just configure/extend the project with my own form of generator that can work with my HalBuilder library ( and its JAX-RS extension ).

**Comment by ddossot** [comment]
The JAX-RS container is mandated to take care of the thread safety of these annotated fields. Depending on the instantiation policy of the resource, it will either use actual instances or thread-local bound values.

So just add:
```java
@Context
private UriInfo uriInfo;
```
in your resource implementation and you will be good.

**Comment by talios** [comment]
Oh cool. +1 will give that a shot.
